export interface OBD2Code {
  code: string;
  category: "P" | "B" | "C" | "U";
  type: "generic" | "manufacturer";
  title: string;
  shortDesc: string;
  symptoms: string[];
  causes: string[];
  severity: "low" | "moderate" | "high" | "critical";
  diyDifficulty: "easy" | "moderate" | "hard" | "professional";
  estimatedRepairCost: { min: number; max: number };
  drivable: boolean;
  affectedSystems: string[];
}

export const OBD2_CODES: OBD2Code[] = [
  // ─── POWERTRAIN — Catalyst / Emissions ───
  {
    code: "P0420",
    category: "P",
    type: "generic",
    title: "Catalyst System Efficiency Below Threshold (Bank 1)",
    shortDesc: "The catalytic converter on engine bank 1 is not converting exhaust gases efficiently enough.",
    symptoms: ["Check engine light on", "Reduced fuel economy", "Sulfur or rotten egg smell from exhaust", "Sluggish acceleration", "Failed emissions test"],
    causes: ["Worn or failing catalytic converter", "Faulty downstream O2 sensor", "Exhaust leak before or near the converter", "Engine misfire fouling the cat", "Wrong fuel or contaminated fuel"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 200, max: 2500 },
    drivable: true,
    affectedSystems: ["Exhaust", "Emissions", "Catalytic Converter", "Oxygen Sensors"],
  },
  {
    code: "P0430",
    category: "P",
    type: "generic",
    title: "Catalyst System Efficiency Below Threshold (Bank 2)",
    shortDesc: "The catalytic converter on engine bank 2 is below required efficiency.",
    symptoms: ["Check engine light on", "Reduced MPG", "Rotten egg odor", "Failed emissions inspection"],
    causes: ["Worn catalytic converter (Bank 2)", "Defective downstream O2 sensor", "Exhaust leak near bank 2 cat", "Misfire on bank 2 cylinders"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 200, max: 2500 },
    drivable: true,
    affectedSystems: ["Exhaust", "Emissions", "Catalytic Converter"],
  },
  {
    code: "P0421",
    category: "P",
    type: "generic",
    title: "Warm Up Catalyst Efficiency Below Threshold (Bank 1)",
    shortDesc: "The warm-up catalyst on bank 1 is slow to reach operating efficiency.",
    symptoms: ["Check engine light", "Higher cold-start emissions", "Mild fuel economy drop"],
    causes: ["Aging warm-up catalyst", "Faulty O2 sensor", "Exhaust leak near manifold"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 250, max: 1800 },
    drivable: true,
    affectedSystems: ["Exhaust", "Emissions"],
  },
  {
    code: "P0431",
    category: "P",
    type: "generic",
    title: "Warm Up Catalyst Efficiency Below Threshold (Bank 2)",
    shortDesc: "Bank 2 warm-up catalyst is not reaching efficiency targets quickly enough.",
    symptoms: ["Check engine light", "Increased cold emissions"],
    causes: ["Aged catalyst", "Bad O2 sensor", "Exhaust leak"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 250, max: 1800 },
    drivable: true,
    affectedSystems: ["Exhaust", "Emissions"],
  },

  // ─── Fuel & Air Metering ───
  {
    code: "P0171",
    category: "P",
    type: "generic",
    title: "System Too Lean (Bank 1)",
    shortDesc: "The engine on bank 1 is running with too much air relative to fuel.",
    symptoms: ["Check engine light", "Rough idle", "Engine hesitation or stumble", "Loss of power", "Hard starting", "Slight misfire"],
    causes: ["Vacuum leak (intake gasket, hoses, PCV)", "Dirty or faulty MAF sensor", "Weak fuel pump or clogged fuel filter", "Leaking fuel injector seal", "Failing O2 sensor", "Stuck-open EGR valve"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 80, max: 800 },
    drivable: true,
    affectedSystems: ["Fuel", "Air Intake", "Emissions"],
  },
  {
    code: "P0174",
    category: "P",
    type: "generic",
    title: "System Too Lean (Bank 2)",
    shortDesc: "Bank 2 of the engine is running lean — too much air, not enough fuel.",
    symptoms: ["Check engine light", "Rough idle", "Hesitation under acceleration", "Reduced power"],
    causes: ["Vacuum leak", "Dirty MAF sensor", "Weak fuel delivery", "Faulty O2 sensor"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 80, max: 800 },
    drivable: true,
    affectedSystems: ["Fuel", "Air Intake"],
  },
  {
    code: "P0172",
    category: "P",
    type: "generic",
    title: "System Too Rich (Bank 1)",
    shortDesc: "Bank 1 is burning too much fuel relative to air.",
    symptoms: ["Black exhaust smoke", "Strong fuel smell", "Poor MPG", "Rough idle", "Fouled spark plugs"],
    causes: ["Leaking fuel injector", "High fuel pressure (bad regulator)", "Faulty MAF or MAP sensor", "Stuck-closed EVAP purge valve", "Contaminated O2 sensor"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 100, max: 900 },
    drivable: true,
    affectedSystems: ["Fuel", "Emissions"],
  },
  {
    code: "P0175",
    category: "P",
    type: "generic",
    title: "System Too Rich (Bank 2)",
    shortDesc: "Bank 2 is running with excess fuel.",
    symptoms: ["Poor fuel economy", "Black smoke", "Rough running", "Strong gas odor"],
    causes: ["Leaking injector on bank 2", "Bad fuel pressure regulator", "Faulty MAF/MAP", "Bad O2 sensor"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 100, max: 900 },
    drivable: true,
    affectedSystems: ["Fuel", "Emissions"],
  },

  // ─── Misfires ───
  {
    code: "P0300",
    category: "P",
    type: "generic",
    title: "Random/Multiple Cylinder Misfire Detected",
    shortDesc: "The engine is misfiring on more than one cylinder, or the misfire is random.",
    symptoms: ["Flashing or solid check engine light", "Rough idle", "Engine shaking", "Loss of power", "Hesitation on acceleration", "Poor fuel economy"],
    causes: ["Worn spark plugs or coils", "Vacuum leak", "Low fuel pressure", "Bad fuel injectors", "Low compression", "Bad timing"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 100, max: 1500 },
    drivable: false,
    affectedSystems: ["Ignition", "Fuel", "Engine"],
  },
  {
    code: "P0301",
    category: "P",
    type: "generic",
    title: "Cylinder 1 Misfire Detected",
    shortDesc: "Cylinder 1 is misfiring — not delivering power consistently.",
    symptoms: ["CEL flashing", "Rough idle", "Engine vibration", "Power loss"],
    causes: ["Bad spark plug", "Faulty ignition coil", "Clogged or stuck injector", "Low compression", "Vacuum leak at runner"],
    severity: "high",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 50, max: 600 },
    drivable: false,
    affectedSystems: ["Ignition", "Fuel"],
  },
  {
    code: "P0302",
    category: "P",
    type: "generic",
    title: "Cylinder 2 Misfire Detected",
    shortDesc: "Cylinder 2 is not firing consistently.",
    symptoms: ["Flashing CEL", "Vibration", "Loss of power"],
    causes: ["Spark plug", "Coil", "Injector", "Compression"],
    severity: "high",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 50, max: 600 },
    drivable: false,
    affectedSystems: ["Ignition", "Fuel"],
  },
  {
    code: "P0303",
    category: "P",
    type: "generic",
    title: "Cylinder 3 Misfire Detected",
    shortDesc: "Cylinder 3 is misfiring.",
    symptoms: ["CEL flashing", "Rough running", "Reduced power"],
    causes: ["Spark plug or coil", "Injector failure", "Low compression"],
    severity: "high",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 50, max: 600 },
    drivable: false,
    affectedSystems: ["Ignition", "Fuel"],
  },
  {
    code: "P0304",
    category: "P",
    type: "generic",
    title: "Cylinder 4 Misfire Detected",
    shortDesc: "Cylinder 4 is not firing reliably.",
    symptoms: ["Flashing CEL", "Rough idle", "Stumble"],
    causes: ["Bad plug or coil", "Injector issue", "Compression loss"],
    severity: "high",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 50, max: 600 },
    drivable: false,
    affectedSystems: ["Ignition", "Fuel"],
  },
  {
    code: "P0305",
    category: "P",
    type: "generic",
    title: "Cylinder 5 Misfire Detected",
    shortDesc: "Cylinder 5 is misfiring.",
    symptoms: ["CEL flashing", "Vibration", "Power loss"],
    causes: ["Plug/coil", "Injector", "Compression"],
    severity: "high",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 50, max: 600 },
    drivable: false,
    affectedSystems: ["Ignition", "Fuel"],
  },
  {
    code: "P0306",
    category: "P",
    type: "generic",
    title: "Cylinder 6 Misfire Detected",
    shortDesc: "Cylinder 6 is misfiring.",
    symptoms: ["Flashing CEL", "Rough idle", "Hesitation"],
    causes: ["Plug or coil", "Injector", "Compression"],
    severity: "high",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 50, max: 600 },
    drivable: false,
    affectedSystems: ["Ignition", "Fuel"],
  },
  {
    code: "P0307",
    category: "P",
    type: "generic",
    title: "Cylinder 7 Misfire Detected",
    shortDesc: "Cylinder 7 is not firing properly (V8 / large engines).",
    symptoms: ["CEL flashing", "Rough idle", "Power loss"],
    causes: ["Plug/coil", "Injector", "Compression"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 60, max: 700 },
    drivable: false,
    affectedSystems: ["Ignition", "Fuel"],
  },
  {
    code: "P0308",
    category: "P",
    type: "generic",
    title: "Cylinder 8 Misfire Detected",
    shortDesc: "Cylinder 8 is misfiring (V8 engines).",
    symptoms: ["Flashing CEL", "Rough running", "Power loss"],
    causes: ["Plug/coil", "Injector", "Compression"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 60, max: 700 },
    drivable: false,
    affectedSystems: ["Ignition", "Fuel"],
  },
  {
    code: "P0316",
    category: "P",
    type: "generic",
    title: "Engine Misfire Detected on Startup (First 1000 Revolutions)",
    shortDesc: "A misfire was detected during the first 1000 revolutions after engine start.",
    symptoms: ["Rough cold start", "CEL", "Brief stumble at startup"],
    causes: ["Cold-soak fuel issue", "Worn plugs", "Weak coil", "Low compression on one cylinder"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 80, max: 800 },
    drivable: true,
    affectedSystems: ["Ignition", "Fuel"],
  },

  // ─── VVT / Camshaft Timing ───
  {
    code: "P0010",
    category: "P",
    type: "generic",
    title: "'A' Camshaft Position Actuator Circuit (Bank 1)",
    shortDesc: "The PCM has detected a circuit fault in the bank 1 intake camshaft position actuator (VVT).",
    symptoms: ["CEL", "Rough idle", "Loss of power at certain RPMs", "Poor fuel economy"],
    causes: ["Failed VVT solenoid", "Wiring or connector issue", "Low/dirty oil", "Failed PCM driver"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 600 },
    drivable: true,
    affectedSystems: ["VVT", "Engine Timing"],
  },
  {
    code: "P0011",
    category: "P",
    type: "generic",
    title: "'A' Camshaft Position - Timing Over-Advanced (Bank 1)",
    shortDesc: "The bank 1 intake camshaft timing is more advanced than commanded.",
    symptoms: ["Check engine light", "Rough idle", "Poor MPG", "Loss of power", "Hard starting"],
    causes: ["Stuck VVT solenoid", "Dirty engine oil clogging oil control valve", "Worn timing chain or guides", "Faulty cam position sensor"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 1500 },
    drivable: true,
    affectedSystems: ["VVT", "Engine Timing", "Lubrication"],
  },
  {
    code: "P0014",
    category: "P",
    type: "generic",
    title: "'B' Camshaft Position - Timing Over-Advanced (Bank 1)",
    shortDesc: "The bank 1 exhaust camshaft is over-advanced relative to commanded position.",
    symptoms: ["CEL", "Rough idle", "Stalling", "Poor performance"],
    causes: ["Stuck/dirty VVT solenoid", "Old oil", "Worn timing chain", "Failed cam sensor"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 1500 },
    drivable: true,
    affectedSystems: ["VVT", "Engine Timing"],
  },
  {
    code: "P0017",
    category: "P",
    type: "generic",
    title: "Crankshaft Position - Camshaft Position Correlation (Bank 1 Sensor B)",
    shortDesc: "Crank and bank 1 exhaust cam position signals are out of sync.",
    symptoms: ["Hard start", "Rough run", "CEL", "Possible stall"],
    causes: ["Stretched timing chain", "Failed VVT actuator", "Sensor failure", "Skipped chain tooth"],
    severity: "high",
    diyDifficulty: "hard",
    estimatedRepairCost: { min: 800, max: 3000 },
    drivable: false,
    affectedSystems: ["Engine Timing", "VVT"],
  },
  {
    code: "P0019",
    category: "P",
    type: "generic",
    title: "Crankshaft Position - Camshaft Position Correlation (Bank 2 Sensor B)",
    shortDesc: "Crank and bank 2 exhaust cam are not properly correlated.",
    symptoms: ["Hard start", "Misfire", "Rough idle"],
    causes: ["Stretched timing chain", "Bad VVT actuator", "Cam sensor"],
    severity: "high",
    diyDifficulty: "hard",
    estimatedRepairCost: { min: 800, max: 3000 },
    drivable: false,
    affectedSystems: ["Engine Timing"],
  },
  {
    code: "P0050",
    category: "P",
    type: "generic",
    title: "HO2S Heater Control Circuit (Bank 2 Sensor 1)",
    shortDesc: "Open or short in the heater circuit of the bank 2 upstream oxygen sensor.",
    symptoms: ["CEL", "Slight MPG drop"],
    causes: ["Bad O2 sensor heater element", "Blown fuse", "Broken wiring"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Emissions", "Oxygen Sensors"],
  },
  {
    code: "P0068",
    category: "P",
    type: "generic",
    title: "MAP/MAF - Throttle Position Correlation",
    shortDesc: "PCM sees a mismatch between airflow sensor and throttle position readings.",
    symptoms: ["CEL", "Stalling", "Limp mode", "Erratic idle"],
    causes: ["Vacuum leak", "Bad MAP/MAF sensor", "Bad throttle body", "Wiring issue"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 100, max: 600 },
    drivable: true,
    affectedSystems: ["Air Intake", "Throttle"],
  },
  {
    code: "P0089",
    category: "P",
    type: "generic",
    title: "Fuel Pressure Regulator Performance",
    shortDesc: "The fuel pressure regulator is not maintaining commanded fuel pressure.",
    symptoms: ["Hard start", "Long crank", "Power loss", "Rough run"],
    causes: ["Faulty fuel pressure regulator", "Weak fuel pump", "Clogged filter", "Leaking injector"],
    severity: "moderate",
    diyDifficulty: "hard",
    estimatedRepairCost: { min: 200, max: 1200 },
    drivable: true,
    affectedSystems: ["Fuel"],
  },

  // ─── Coolant temp / thermostat ───
  {
    code: "P0128",
    category: "P",
    type: "generic",
    title: "Coolant Temperature Below Thermostat Regulating Temperature",
    shortDesc: "Engine isn't reaching its target operating temperature within the expected time.",
    symptoms: ["CEL", "Heater takes a long time to warm", "Slightly worse MPG", "Cold-running engine"],
    causes: ["Stuck-open thermostat", "Faulty coolant temperature sensor", "Low coolant level"],
    severity: "low",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 100, max: 500 },
    drivable: true,
    affectedSystems: ["Cooling"],
  },
  {
    code: "P0125",
    category: "P",
    type: "generic",
    title: "Insufficient Coolant Temperature for Closed Loop Fuel Control",
    shortDesc: "The engine is not warming up enough to enter closed-loop fuel control.",
    symptoms: ["Slow warm-up", "Rough running while cold", "CEL"],
    causes: ["Stuck-open thermostat", "Bad ECT sensor", "Low coolant"],
    severity: "low",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 100, max: 450 },
    drivable: true,
    affectedSystems: ["Cooling", "Fuel"],
  },

  // ─── MAF / IAT / Sensor circuits ───
  {
    code: "P0101",
    category: "P",
    type: "generic",
    title: "Mass or Volume Air Flow Circuit Range/Performance",
    shortDesc: "MAF sensor reading is outside the expected range.",
    symptoms: ["CEL", "Rough idle", "Hesitation", "Stalling", "Poor MPG"],
    causes: ["Dirty MAF sensor", "Air filter clogged", "Vacuum leak", "Intake leak after MAF"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 30, max: 350 },
    drivable: true,
    affectedSystems: ["Air Intake"],
  },
  {
    code: "P0102",
    category: "P",
    type: "generic",
    title: "MAF Circuit Low Input",
    shortDesc: "MAF sensor signal voltage is too low.",
    symptoms: ["CEL", "Hesitation", "Stalling"],
    causes: ["Dirty/failed MAF", "Wiring fault", "Bad connector", "Air leak"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 30, max: 350 },
    drivable: true,
    affectedSystems: ["Air Intake"],
  },
  {
    code: "P0113",
    category: "P",
    type: "generic",
    title: "Intake Air Temperature Circuit High Input",
    shortDesc: "IAT sensor is reporting an abnormally high voltage (open circuit).",
    symptoms: ["CEL", "Slight performance change in cold weather"],
    causes: ["Open in IAT wiring", "Bad IAT sensor", "Bad connector"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 30, max: 200 },
    drivable: true,
    affectedSystems: ["Air Intake"],
  },
  {
    code: "P0117",
    category: "P",
    type: "generic",
    title: "Engine Coolant Temperature Circuit Low Input",
    shortDesc: "ECT sensor signal is reading too low (sensor short).",
    symptoms: ["CEL", "Hard cold starts", "Black smoke (rich)"],
    causes: ["Shorted ECT sensor", "Wiring shorted to ground"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 50, max: 250 },
    drivable: true,
    affectedSystems: ["Cooling"],
  },
  {
    code: "P0118",
    category: "P",
    type: "generic",
    title: "Engine Coolant Temperature Circuit High Input",
    shortDesc: "Coolant temp sensor reads abnormally high voltage (open or out of range).",
    symptoms: ["CEL", "Cooling fan running constantly", "Hard start", "Bad MPG"],
    causes: ["Open ECT sensor", "Disconnected connector", "Wiring break"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 50, max: 250 },
    drivable: true,
    affectedSystems: ["Cooling"],
  },
  {
    code: "P0121",
    category: "P",
    type: "generic",
    title: "Throttle Position Sensor 'A' Circuit Range/Performance",
    shortDesc: "TPS signal does not match expected throttle plate position.",
    symptoms: ["CEL", "Hesitation", "Limp mode", "Erratic idle"],
    causes: ["Dirty throttle body", "Bad TPS", "Wiring issue"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 80, max: 500 },
    drivable: true,
    affectedSystems: ["Throttle"],
  },
  {
    code: "P0122",
    category: "P",
    type: "generic",
    title: "Throttle Position Sensor 'A' Circuit Low Input",
    shortDesc: "TPS voltage is too low.",
    symptoms: ["CEL", "Limp mode", "No throttle response"],
    causes: ["Bad TPS", "Shorted wire", "Bad ground"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 80, max: 500 },
    drivable: true,
    affectedSystems: ["Throttle"],
  },
  {
    code: "P0123",
    category: "P",
    type: "generic",
    title: "Throttle Position Sensor 'A' Circuit High Input",
    shortDesc: "TPS voltage is too high (above expected range).",
    symptoms: ["CEL", "High idle", "Limp mode"],
    causes: ["Failed TPS", "Wiring issue", "Bad connector"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 80, max: 500 },
    drivable: true,
    affectedSystems: ["Throttle"],
  },

  // ─── Oxygen sensors ───
  {
    code: "P0131",
    category: "P",
    type: "generic",
    title: "O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)",
    shortDesc: "Upstream O2 sensor on bank 1 is reading abnormally low.",
    symptoms: ["CEL", "Bad MPG", "Failed emissions"],
    causes: ["Failed O2 sensor", "Exhaust leak", "Bad wiring", "Lean fuel condition"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors", "Emissions"],
  },
  {
    code: "P0132",
    category: "P",
    type: "generic",
    title: "O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)",
    shortDesc: "Upstream O2 sensor (bank 1) is reading too high.",
    symptoms: ["CEL", "Black smoke", "Poor MPG"],
    causes: ["Shorted sensor", "Rich condition", "Wiring fault"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0133",
    category: "P",
    type: "generic",
    title: "O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)",
    shortDesc: "Upstream O2 sensor is responding too slowly to fuel mixture changes.",
    symptoms: ["CEL", "Reduced MPG"],
    causes: ["Aging O2 sensor", "Exhaust leak", "Contaminated sensor"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 150, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0134",
    category: "P",
    type: "generic",
    title: "O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 1)",
    shortDesc: "Upstream O2 sensor on bank 1 isn't producing signal activity.",
    symptoms: ["CEL", "Worse MPG"],
    causes: ["Dead O2 sensor", "Open circuit", "No exhaust flow past sensor"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 150, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0135",
    category: "P",
    type: "generic",
    title: "O2 Sensor Heater Circuit (Bank 1 Sensor 1)",
    shortDesc: "Bank 1, sensor 1 oxygen sensor heater circuit failure.",
    symptoms: ["CEL", "Slight MPG drop"],
    causes: ["Failed heater element", "Blown fuse", "Wiring fault"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0136",
    category: "P",
    type: "generic",
    title: "O2 Sensor Circuit Malfunction (Bank 1 Sensor 2)",
    shortDesc: "Downstream O2 sensor on bank 1 has a circuit malfunction.",
    symptoms: ["CEL"],
    causes: ["Bad downstream O2 sensor", "Wiring/connector issue"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0138",
    category: "P",
    type: "generic",
    title: "O2 Sensor Circuit High Voltage (Bank 1 Sensor 2)",
    shortDesc: "Downstream bank 1 O2 sensor reads too high.",
    symptoms: ["CEL", "Possible MPG drop"],
    causes: ["Sensor short", "Rich condition", "Bad wiring"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0139",
    category: "P",
    type: "generic",
    title: "O2 Sensor Slow Response (Bank 1 Sensor 2)",
    shortDesc: "Downstream bank 1 O2 sensor switching slowly.",
    symptoms: ["CEL"],
    causes: ["Aging sensor", "Exhaust leak"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0140",
    category: "P",
    type: "generic",
    title: "O2 Sensor No Activity Detected (Bank 1 Sensor 2)",
    shortDesc: "Downstream sensor on bank 1 has no signal activity.",
    symptoms: ["CEL"],
    causes: ["Dead sensor", "Open wiring", "Disconnected sensor"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0141",
    category: "P",
    type: "generic",
    title: "O2 Sensor Heater Circuit (Bank 1 Sensor 2)",
    shortDesc: "Heater circuit fault in the downstream bank 1 oxygen sensor.",
    symptoms: ["CEL", "Slow O2 readiness for emissions test"],
    causes: ["Failed heater element", "Blown fuse", "Wiring break"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0151",
    category: "P",
    type: "generic",
    title: "O2 Sensor Circuit Low Voltage (Bank 2 Sensor 1)",
    shortDesc: "Bank 2 upstream O2 sensor reads abnormally low.",
    symptoms: ["CEL", "Lean condition codes"],
    causes: ["Failed sensor", "Exhaust leak", "Lean fuel"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0152",
    category: "P",
    type: "generic",
    title: "O2 Sensor Circuit High Voltage (Bank 2 Sensor 1)",
    shortDesc: "Bank 2 upstream O2 sensor reads too high.",
    symptoms: ["CEL", "Rich condition"],
    causes: ["Sensor short", "Rich fuel", "Bad wiring"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0153",
    category: "P",
    type: "generic",
    title: "O2 Sensor Slow Response (Bank 2 Sensor 1)",
    shortDesc: "Bank 2 upstream O2 sensor reacting too slowly.",
    symptoms: ["CEL", "MPG drop"],
    causes: ["Aging sensor", "Exhaust leak"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 150, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0155",
    category: "P",
    type: "generic",
    title: "O2 Sensor Heater Circuit (Bank 2 Sensor 1)",
    shortDesc: "Heater circuit fault on bank 2 upstream O2 sensor.",
    symptoms: ["CEL"],
    causes: ["Heater element open", "Bad fuse", "Wiring break"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0156",
    category: "P",
    type: "generic",
    title: "O2 Sensor Circuit Malfunction (Bank 2 Sensor 2)",
    shortDesc: "Downstream bank 2 O2 sensor circuit malfunction.",
    symptoms: ["CEL"],
    causes: ["Bad sensor", "Wiring issue"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0158",
    category: "P",
    type: "generic",
    title: "O2 Sensor Circuit High Voltage (Bank 2 Sensor 2)",
    shortDesc: "Downstream bank 2 O2 sensor signal abnormally high.",
    symptoms: ["CEL"],
    causes: ["Bad sensor", "Rich condition"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P0161",
    category: "P",
    type: "generic",
    title: "O2 Sensor Heater Circuit (Bank 2 Sensor 2)",
    shortDesc: "Heater circuit fault in downstream bank 2 oxygen sensor.",
    symptoms: ["CEL"],
    causes: ["Heater open", "Fuse", "Wiring"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },

  // ─── Fuel rail / injector ───
  {
    code: "P0190",
    category: "P",
    type: "generic",
    title: "Fuel Rail Pressure Sensor Circuit Malfunction",
    shortDesc: "Issue with the fuel rail pressure sensor signal.",
    symptoms: ["Hard start", "Stalling", "Power loss", "CEL"],
    causes: ["Bad fuel rail pressure sensor", "Wiring issue", "Connector"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 600 },
    drivable: true,
    affectedSystems: ["Fuel"],
  },
  {
    code: "P0191",
    category: "P",
    type: "generic",
    title: "Fuel Rail Pressure Sensor Circuit Range/Performance",
    shortDesc: "Fuel rail pressure sensor reading outside expected range.",
    symptoms: ["Power loss", "Stalling", "CEL"],
    causes: ["Sensor failure", "Weak fuel pump", "Pressure regulator"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 200, max: 1000 },
    drivable: true,
    affectedSystems: ["Fuel"],
  },
  {
    code: "P0193",
    category: "P",
    type: "generic",
    title: "Fuel Rail Pressure Sensor Circuit High Input",
    shortDesc: "Fuel rail pressure sensor voltage is too high.",
    symptoms: ["Hard start", "Rich/black smoke", "CEL"],
    causes: ["Failed sensor", "Wiring short", "Bad regulator"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 200, max: 800 },
    drivable: true,
    affectedSystems: ["Fuel"],
  },
  {
    code: "P0200",
    category: "P",
    type: "generic",
    title: "Injector Circuit Malfunction",
    shortDesc: "An injector control circuit has a fault.",
    symptoms: ["Misfire", "Rough idle", "CEL"],
    causes: ["Failed injector", "Wiring fault", "Bad PCM driver"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 900 },
    drivable: false,
    affectedSystems: ["Fuel"],
  },
  {
    code: "P0201",
    category: "P",
    type: "generic",
    title: "Injector Circuit Malfunction - Cylinder 1",
    shortDesc: "Cylinder 1 injector circuit fault.",
    symptoms: ["Misfire on cyl 1", "Rough idle"],
    causes: ["Bad injector", "Wiring/connector"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 700 },
    drivable: false,
    affectedSystems: ["Fuel"],
  },
  {
    code: "P0202",
    category: "P",
    type: "generic",
    title: "Injector Circuit Malfunction - Cylinder 2",
    shortDesc: "Cylinder 2 injector circuit fault.",
    symptoms: ["Misfire on cyl 2", "Rough run"],
    causes: ["Bad injector", "Wiring"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 700 },
    drivable: false,
    affectedSystems: ["Fuel"],
  },
  {
    code: "P0203",
    category: "P",
    type: "generic",
    title: "Injector Circuit Malfunction - Cylinder 3",
    shortDesc: "Cylinder 3 injector circuit fault.",
    symptoms: ["Misfire", "Rough idle"],
    causes: ["Injector", "Wiring"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 700 },
    drivable: false,
    affectedSystems: ["Fuel"],
  },
  {
    code: "P0204",
    category: "P",
    type: "generic",
    title: "Injector Circuit Malfunction - Cylinder 4",
    shortDesc: "Cylinder 4 injector circuit fault.",
    symptoms: ["Misfire", "Rough idle"],
    causes: ["Injector", "Wiring"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 700 },
    drivable: false,
    affectedSystems: ["Fuel"],
  },
  {
    code: "P0299",
    category: "P",
    type: "generic",
    title: "Turbocharger/Supercharger Underboost Condition",
    shortDesc: "The turbo or supercharger is producing less boost than commanded.",
    symptoms: ["Power loss", "Limp mode", "CEL", "Sluggish acceleration"],
    causes: ["Boost leak", "Failing turbo", "Bad wastegate", "Bad boost solenoid", "Cracked intercooler hose"],
    severity: "high",
    diyDifficulty: "hard",
    estimatedRepairCost: { min: 150, max: 3000 },
    drivable: true,
    affectedSystems: ["Forced Induction", "Air Intake"],
  },

  // ─── Crank/Cam sensors & ignition ───
  {
    code: "P0335",
    category: "P",
    type: "generic",
    title: "Crankshaft Position Sensor 'A' Circuit Malfunction",
    shortDesc: "Crankshaft position sensor circuit problem.",
    symptoms: ["No-start", "Stalling", "Hard start", "CEL"],
    causes: ["Failed crank sensor", "Wiring issue", "Reluctor wheel damage"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 500 },
    drivable: false,
    affectedSystems: ["Ignition", "Engine Sensors"],
  },
  {
    code: "P0336",
    category: "P",
    type: "generic",
    title: "Crankshaft Position Sensor 'A' Circuit Range/Performance",
    shortDesc: "Crank sensor signal outside expected range.",
    symptoms: ["Stalling", "Misfire", "Hard start"],
    causes: ["Sensor", "Reluctor", "Wiring"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 500 },
    drivable: true,
    affectedSystems: ["Ignition"],
  },
  {
    code: "P0340",
    category: "P",
    type: "generic",
    title: "Camshaft Position Sensor 'A' Circuit Malfunction",
    shortDesc: "Camshaft position sensor circuit fault.",
    symptoms: ["Hard start", "Stall", "CEL", "Rough run"],
    causes: ["Failed cam sensor", "Wiring", "Bad timing components"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 500 },
    drivable: true,
    affectedSystems: ["Engine Timing", "Ignition"],
  },
  {
    code: "P0341",
    category: "P",
    type: "generic",
    title: "Camshaft Position Sensor 'A' Circuit Range/Performance",
    shortDesc: "Cam sensor signal performance issue.",
    symptoms: ["Hard start", "Stall", "CEL"],
    causes: ["Cam sensor", "Wiring", "Timing chain stretch"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 1500 },
    drivable: true,
    affectedSystems: ["Engine Timing"],
  },
  {
    code: "P0342",
    category: "P",
    type: "generic",
    title: "Camshaft Position Sensor 'A' Circuit Low Input",
    shortDesc: "Cam sensor signal voltage too low.",
    symptoms: ["Stall", "Hard start"],
    causes: ["Cam sensor", "Shorted wiring"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 500 },
    drivable: true,
    affectedSystems: ["Engine Timing"],
  },
  {
    code: "P0343",
    category: "P",
    type: "generic",
    title: "Camshaft Position Sensor 'A' Circuit High Input",
    shortDesc: "Cam sensor signal voltage too high.",
    symptoms: ["Stall", "CEL"],
    causes: ["Sensor failure", "Open wiring"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 500 },
    drivable: true,
    affectedSystems: ["Engine Timing"],
  },
  {
    code: "P0351",
    category: "P",
    type: "generic",
    title: "Ignition Coil 'A' Primary/Secondary Circuit Malfunction",
    shortDesc: "Ignition coil for cylinder 1 (or coil A) has a circuit fault.",
    symptoms: ["Misfire on cyl 1", "Rough run", "CEL flashing"],
    causes: ["Failed coil", "Wiring", "Bad connector"],
    severity: "high",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 60, max: 350 },
    drivable: false,
    affectedSystems: ["Ignition"],
  },
  {
    code: "P0352",
    category: "P",
    type: "generic",
    title: "Ignition Coil 'B' Primary/Secondary Circuit Malfunction",
    shortDesc: "Coil B (commonly cyl 2) circuit fault.",
    symptoms: ["Misfire", "Rough run"],
    causes: ["Coil failure", "Wiring"],
    severity: "high",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 60, max: 350 },
    drivable: false,
    affectedSystems: ["Ignition"],
  },
  {
    code: "P0353",
    category: "P",
    type: "generic",
    title: "Ignition Coil 'C' Primary/Secondary Circuit Malfunction",
    shortDesc: "Coil C (cyl 3 typically) circuit issue.",
    symptoms: ["Misfire", "Rough idle"],
    causes: ["Coil failure", "Wiring"],
    severity: "high",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 60, max: 350 },
    drivable: false,
    affectedSystems: ["Ignition"],
  },
  {
    code: "P0354",
    category: "P",
    type: "generic",
    title: "Ignition Coil 'D' Primary/Secondary Circuit Malfunction",
    shortDesc: "Coil D (cyl 4 typically) circuit issue.",
    symptoms: ["Misfire", "Rough run"],
    causes: ["Coil", "Wiring"],
    severity: "high",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 60, max: 350 },
    drivable: false,
    affectedSystems: ["Ignition"],
  },

  // ─── EVAP ───
  {
    code: "P0440",
    category: "P",
    type: "generic",
    title: "Evaporative Emission Control System Malfunction",
    shortDesc: "A general fault in the EVAP system that captures fuel vapors.",
    symptoms: ["CEL", "Fuel smell", "Failed emissions"],
    causes: ["Loose or bad gas cap", "EVAP hose leak", "Bad purge valve", "Bad vent valve"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 20, max: 400 },
    drivable: true,
    affectedSystems: ["EVAP", "Emissions"],
  },
  {
    code: "P0441",
    category: "P",
    type: "generic",
    title: "EVAP System Incorrect Purge Flow",
    shortDesc: "Purge flow in the EVAP system is wrong.",
    symptoms: ["CEL"],
    causes: ["Stuck purge valve", "EVAP hose disconnected", "Bad vent valve"],
    severity: "low",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 80, max: 500 },
    drivable: true,
    affectedSystems: ["EVAP"],
  },
  {
    code: "P0442",
    category: "P",
    type: "generic",
    title: "EVAP System Small Leak Detected",
    shortDesc: "A small leak (often 0.040\") detected in the EVAP system.",
    symptoms: ["CEL", "Possible fuel smell"],
    causes: ["Loose gas cap", "Cracked EVAP hose", "Bad gas cap seal"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 20, max: 400 },
    drivable: true,
    affectedSystems: ["EVAP"],
  },
  {
    code: "P0443",
    category: "P",
    type: "generic",
    title: "EVAP Purge Control Valve Circuit",
    shortDesc: "Circuit fault in the EVAP purge control valve.",
    symptoms: ["CEL"],
    causes: ["Bad purge valve", "Wiring fault"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 60, max: 250 },
    drivable: true,
    affectedSystems: ["EVAP"],
  },
  {
    code: "P0446",
    category: "P",
    type: "generic",
    title: "EVAP Vent Control Circuit",
    shortDesc: "Vent valve circuit fault in EVAP system.",
    symptoms: ["CEL", "Hard refueling (clicks off pump)"],
    causes: ["Bad vent solenoid", "Wiring issue"],
    severity: "low",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["EVAP"],
  },
  {
    code: "P0455",
    category: "P",
    type: "generic",
    title: "EVAP System Large Leak Detected",
    shortDesc: "A large leak (often 0.090\" or larger) detected in the EVAP system.",
    symptoms: ["CEL", "Fuel vapor smell"],
    causes: ["Missing or loose gas cap", "Cracked or disconnected EVAP hose", "Failed EVAP canister"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 20, max: 500 },
    drivable: true,
    affectedSystems: ["EVAP"],
  },
  {
    code: "P0456",
    category: "P",
    type: "generic",
    title: "EVAP System Very Small Leak Detected",
    shortDesc: "A very small leak (often 0.020\") detected in the EVAP system.",
    symptoms: ["CEL"],
    causes: ["Slightly loose gas cap", "Aging cap seal", "Tiny hose crack", "Failed purge solenoid"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 20, max: 400 },
    drivable: true,
    affectedSystems: ["EVAP"],
  },
  {
    code: "P0457",
    category: "P",
    type: "generic",
    title: "EVAP Leak Detected (Fuel Cap Loose/Off)",
    shortDesc: "EVAP leak detected, often related to fuel cap.",
    symptoms: ["CEL"],
    causes: ["Loose fuel cap", "Bad cap seal"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 0, max: 50 },
    drivable: true,
    affectedSystems: ["EVAP"],
  },

  // ─── EGR ───
  {
    code: "P0401",
    category: "P",
    type: "generic",
    title: "Exhaust Gas Recirculation Flow Insufficient",
    shortDesc: "EGR system isn't flowing enough exhaust back into the intake.",
    symptoms: ["CEL", "Pinging/knock", "Rough idle", "Failed emissions"],
    causes: ["Clogged EGR passages", "Bad EGR valve", "Bad DPFE sensor"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 100, max: 600 },
    drivable: true,
    affectedSystems: ["EGR", "Emissions"],
  },
  {
    code: "P0402",
    category: "P",
    type: "generic",
    title: "EGR Flow Excessive",
    shortDesc: "Too much exhaust is being recirculated.",
    symptoms: ["CEL", "Stalling", "Rough idle"],
    causes: ["Stuck-open EGR valve", "Carbon buildup", "Bad sensor"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 100, max: 500 },
    drivable: true,
    affectedSystems: ["EGR"],
  },
  {
    code: "P0404",
    category: "P",
    type: "generic",
    title: "EGR Control Circuit Range/Performance",
    shortDesc: "EGR control circuit performance is out of spec.",
    symptoms: ["CEL"],
    causes: ["Bad EGR valve", "Wiring", "Carbon buildup"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 600 },
    drivable: true,
    affectedSystems: ["EGR"],
  },
  {
    code: "P0411",
    category: "P",
    type: "generic",
    title: "Secondary Air Injection System Incorrect Flow Detected",
    shortDesc: "The secondary air injection system isn't flowing the expected amount of air into the exhaust at startup.",
    symptoms: ["CEL", "Possible cold-start emissions issue"],
    causes: ["Failed secondary air pump", "Stuck check valve", "Vacuum leak", "Wiring fault"],
    severity: "low",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 100, max: 900 },
    drivable: true,
    affectedSystems: ["Emissions", "Secondary Air"],
  },

  // ─── Vehicle speed / idle / cruise ───
  {
    code: "P0500",
    category: "P",
    type: "generic",
    title: "Vehicle Speed Sensor Malfunction",
    shortDesc: "PCM is not receiving a valid speed signal.",
    symptoms: ["Speedometer not working", "ABS light on", "Cruise control inoperative", "CEL"],
    causes: ["Bad VSS", "Wiring fault", "Bad ABS sensor"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["Powertrain", "ABS"],
  },
  {
    code: "P0506",
    category: "P",
    type: "generic",
    title: "Idle Air Control System RPM Lower Than Expected",
    shortDesc: "Engine idle is lower than commanded.",
    symptoms: ["Stalling at idle", "Low idle RPM", "Rough idle"],
    causes: ["Dirty throttle body", "Vacuum leak", "Bad IAC valve"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 80, max: 400 },
    drivable: true,
    affectedSystems: ["Idle Control"],
  },
  {
    code: "P0507",
    category: "P",
    type: "generic",
    title: "Idle Air Control System RPM Higher Than Expected",
    shortDesc: "Engine idle is higher than commanded.",
    symptoms: ["High idle", "Won't return to normal idle"],
    causes: ["Vacuum leak", "Dirty throttle body", "Stuck IAC valve", "Failed PCV"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 80, max: 400 },
    drivable: true,
    affectedSystems: ["Idle Control"],
  },

  // ─── Battery / Charging ───
  {
    code: "P0560",
    category: "P",
    type: "generic",
    title: "System Voltage Malfunction",
    shortDesc: "PCM detected an abnormal system voltage.",
    symptoms: ["CEL", "Battery light", "Stalling"],
    causes: ["Failing alternator", "Bad battery", "Loose battery cable"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 600 },
    drivable: true,
    affectedSystems: ["Charging", "Electrical"],
  },
  {
    code: "P0562",
    category: "P",
    type: "generic",
    title: "System Voltage Low",
    shortDesc: "System voltage below operating threshold.",
    symptoms: ["Battery light", "Slow crank", "CEL"],
    causes: ["Bad alternator", "Weak battery", "Corroded cables"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 100, max: 600 },
    drivable: true,
    affectedSystems: ["Charging"],
  },
  {
    code: "P0606",
    category: "P",
    type: "generic",
    title: "ECM/PCM Processor Fault",
    shortDesc: "Internal failure in the engine control module.",
    symptoms: ["CEL", "Limp mode", "Performance issues"],
    causes: ["Failed PCM", "Power/ground issue", "Software corruption"],
    severity: "high",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 400, max: 2000 },
    drivable: true,
    affectedSystems: ["PCM", "Electrical"],
  },

  // ─── Transmission ───
  {
    code: "P0700",
    category: "P",
    type: "generic",
    title: "Transmission Control System Malfunction",
    shortDesc: "Generic transmission control fault — sets along with another more specific TCM code.",
    symptoms: ["CEL", "Limp mode", "Hard or delayed shifts"],
    causes: ["Internal trans fault (see paired code)", "TCM issue", "Wiring"],
    severity: "high",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 200, max: 4000 },
    drivable: true,
    affectedSystems: ["Transmission"],
  },
  {
    code: "P0715",
    category: "P",
    type: "generic",
    title: "Input/Turbine Speed Sensor Circuit Malfunction",
    shortDesc: "Trans input/turbine speed sensor signal fault.",
    symptoms: ["Harsh shifting", "Limp mode", "CEL"],
    causes: ["Bad input speed sensor", "Wiring"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 600 },
    drivable: true,
    affectedSystems: ["Transmission"],
  },
  {
    code: "P0720",
    category: "P",
    type: "generic",
    title: "Output Speed Sensor Circuit Malfunction",
    shortDesc: "Trans output speed sensor signal fault.",
    symptoms: ["Speedometer issues", "Harsh shifts", "CEL"],
    causes: ["Bad output sensor", "Wiring"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 600 },
    drivable: true,
    affectedSystems: ["Transmission"],
  },
  {
    code: "P0730",
    category: "P",
    type: "generic",
    title: "Incorrect Gear Ratio",
    shortDesc: "Transmission gear ratio doesn't match commanded.",
    symptoms: ["Slipping", "Harsh or wrong shift", "CEL"],
    causes: ["Worn clutches", "Low fluid", "Solenoid issue"],
    severity: "high",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 200, max: 4000 },
    drivable: false,
    affectedSystems: ["Transmission"],
  },
  {
    code: "P0731",
    category: "P",
    type: "generic",
    title: "Incorrect Gear Ratio (1st Gear)",
    shortDesc: "1st gear ratio is not as expected.",
    symptoms: ["Slipping in 1st", "Harsh first shift"],
    causes: ["Worn clutch", "Solenoid", "Low fluid"],
    severity: "high",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 200, max: 4000 },
    drivable: false,
    affectedSystems: ["Transmission"],
  },
  {
    code: "P0741",
    category: "P",
    type: "generic",
    title: "Torque Converter Clutch Circuit Performance",
    shortDesc: "TCC isn't applying or releasing as commanded.",
    symptoms: ["Shudder at cruise", "Stall when stopping", "CEL"],
    causes: ["Bad TCC solenoid", "Internal TCC failure", "Dirty fluid"],
    severity: "high",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 300, max: 3000 },
    drivable: true,
    affectedSystems: ["Transmission"],
  },
  {
    code: "P0750",
    category: "P",
    type: "generic",
    title: "Shift Solenoid 'A' Malfunction",
    shortDesc: "Shift solenoid A circuit malfunction.",
    symptoms: ["Harsh shifts", "Stuck in gear", "Limp mode"],
    causes: ["Bad solenoid", "Wiring", "Dirty fluid"],
    severity: "high",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 300, max: 1500 },
    drivable: true,
    affectedSystems: ["Transmission"],
  },
  {
    code: "P0755",
    category: "P",
    type: "generic",
    title: "Shift Solenoid 'B' Malfunction",
    shortDesc: "Shift solenoid B circuit malfunction.",
    symptoms: ["Hard shifts", "Stuck gear"],
    causes: ["Solenoid", "Wiring", "Fluid"],
    severity: "high",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 300, max: 1500 },
    drivable: true,
    affectedSystems: ["Transmission"],
  },

  // ─── Larger P2xxx ───
  {
    code: "P2096",
    category: "P",
    type: "generic",
    title: "Post Catalyst Fuel Trim System Too Lean (Bank 1)",
    shortDesc: "Downstream fuel trim on bank 1 indicates a lean condition.",
    symptoms: ["CEL", "Slight performance issue"],
    causes: ["Exhaust leak", "Bad downstream O2", "Aging cat"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 800 },
    drivable: true,
    affectedSystems: ["Exhaust", "Emissions"],
  },
  {
    code: "P2097",
    category: "P",
    type: "generic",
    title: "Post Catalyst Fuel Trim System Too Rich (Bank 1)",
    shortDesc: "Downstream fuel trim on bank 1 indicates a rich condition.",
    symptoms: ["CEL", "MPG drop"],
    causes: ["Bad O2 sensor", "Cat issue", "Rich fuel"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 800 },
    drivable: true,
    affectedSystems: ["Exhaust"],
  },
  {
    code: "P2195",
    category: "P",
    type: "generic",
    title: "O2 Sensor Signal Stuck Lean (Bank 1 Sensor 1)",
    shortDesc: "Upstream bank 1 O2 sensor signal is stuck reading lean.",
    symptoms: ["CEL", "MPG drop"],
    causes: ["Failing wideband O2 sensor", "Exhaust leak", "True lean condition"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 150, max: 500 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P2270",
    category: "P",
    type: "generic",
    title: "O2 Sensor Signal Stuck Lean (Bank 1 Sensor 2)",
    shortDesc: "Downstream bank 1 O2 sensor stuck lean.",
    symptoms: ["CEL"],
    causes: ["Bad sensor", "Exhaust leak"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 150, max: 500 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },

  // ─── P1xxx Manufacturer-specific common ones ───
  {
    code: "P1000",
    category: "P",
    type: "manufacturer",
    title: "OBD II Monitor Testing Not Complete (Ford / Mazda / Jaguar)",
    shortDesc: "Drive cycle has not been completed since the PCM was reset; readiness monitors are not yet set.",
    symptoms: ["No CEL but readiness incomplete", "Will fail emissions inspection until drive cycle complete"],
    causes: ["Recent battery disconnect", "Recently cleared codes", "Insufficient drive time"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 0, max: 0 },
    drivable: true,
    affectedSystems: ["OBD-II Readiness"],
  },
  {
    code: "P1101",
    category: "P",
    type: "manufacturer",
    title: "MAF Sensor Out of Self Test Range (GM / Ford)",
    shortDesc: "Mass air flow sensor signal out of range during self-test.",
    symptoms: ["CEL", "Hesitation", "Stalling", "Hard start"],
    causes: ["Dirty MAF", "Vacuum leak", "Bad PCV", "Failed MAF"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 30, max: 400 },
    drivable: true,
    affectedSystems: ["Air Intake"],
  },
  {
    code: "P1133",
    category: "P",
    type: "manufacturer",
    title: "HO2S Insufficient Switching (Ford)",
    shortDesc: "Upstream O2 sensor not switching often enough between rich and lean.",
    symptoms: ["CEL"],
    causes: ["Aging O2 sensor", "Exhaust leak"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 150, max: 400 },
    drivable: true,
    affectedSystems: ["Oxygen Sensors"],
  },
  {
    code: "P1399",
    category: "P",
    type: "manufacturer",
    title: "Random Cylinder Misfire Detected (Honda)",
    shortDesc: "Honda-specific random misfire code, similar to P0300.",
    symptoms: ["CEL flashing", "Rough run", "Power loss"],
    causes: ["Worn plugs/coils", "Vacuum leak", "Low fuel pressure"],
    severity: "high",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 100, max: 1000 },
    drivable: false,
    affectedSystems: ["Ignition", "Fuel"],
  },
  {
    code: "P1494",
    category: "P",
    type: "manufacturer",
    title: "EVAP Leak Detection Pump Switch Sense Circuit (Chrysler)",
    shortDesc: "Chrysler-specific code for the EVAP leak detection pump switch.",
    symptoms: ["CEL"],
    causes: ["Bad LDP pump", "Wiring", "Loose gas cap"],
    severity: "low",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 80, max: 400 },
    drivable: true,
    affectedSystems: ["EVAP"],
  },
  {
    code: "P1684",
    category: "P",
    type: "manufacturer",
    title: "Battery Disconnected Within Last 50 Starts (Chrysler)",
    shortDesc: "Chrysler informational code logged after battery disconnect or PCM reset.",
    symptoms: ["No driveability issue"],
    causes: ["Recent battery disconnect", "PCM reset"],
    severity: "low",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 0, max: 0 },
    drivable: true,
    affectedSystems: ["Powertrain"],
  },

  // ─── BODY codes ───
  {
    code: "B0001",
    category: "B",
    type: "generic",
    title: "Driver Frontal Stage 1 Deployment Control",
    shortDesc: "Fault in driver airbag deployment control circuit.",
    symptoms: ["Airbag light on", "SRS warning", "Possible airbag disabled"],
    causes: ["Faulty airbag module", "Wiring/clockspring", "Bad connector"],
    severity: "critical",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 300, max: 2500 },
    drivable: true,
    affectedSystems: ["Airbag/SRS", "Safety"],
  },
  {
    code: "B0002",
    category: "B",
    type: "generic",
    title: "Driver Frontal Stage 2 Deployment Control",
    shortDesc: "Fault in stage 2 driver airbag deployment circuit.",
    symptoms: ["Airbag warning", "SRS light"],
    causes: ["Airbag module", "Clockspring", "Wiring"],
    severity: "critical",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 300, max: 2500 },
    drivable: true,
    affectedSystems: ["Airbag/SRS"],
  },
  {
    code: "B0010",
    category: "B",
    type: "generic",
    title: "Passenger Frontal Stage 1 Deployment Control",
    shortDesc: "Passenger airbag deployment circuit fault.",
    symptoms: ["SRS light", "Passenger airbag disabled"],
    causes: ["Module", "Wiring", "Seat occupancy sensor"],
    severity: "critical",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 300, max: 2500 },
    drivable: true,
    affectedSystems: ["Airbag/SRS"],
  },
  {
    code: "B0020",
    category: "B",
    type: "generic",
    title: "Side Curtain Airbag Deployment Control",
    shortDesc: "Curtain airbag deployment circuit fault.",
    symptoms: ["SRS light"],
    causes: ["Curtain airbag module", "Wiring"],
    severity: "critical",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 400, max: 2500 },
    drivable: true,
    affectedSystems: ["Airbag/SRS"],
  },
  {
    code: "B1000",
    category: "B",
    type: "generic",
    title: "ECU Malfunction (Body)",
    shortDesc: "Internal body control module fault.",
    symptoms: ["Multiple body electrical issues", "Lights/locks/windows malfunctions"],
    causes: ["BCM failure", "Power/ground", "Software"],
    severity: "moderate",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 300, max: 1500 },
    drivable: true,
    affectedSystems: ["Body Control Module"],
  },
  {
    code: "B1318",
    category: "B",
    type: "generic",
    title: "Battery Voltage Low (Body)",
    shortDesc: "BCM detects battery voltage too low.",
    symptoms: ["Body warning lights", "Erratic accessories"],
    causes: ["Weak battery", "Bad alternator", "Parasitic draw"],
    severity: "moderate",
    diyDifficulty: "easy",
    estimatedRepairCost: { min: 150, max: 600 },
    drivable: true,
    affectedSystems: ["Charging", "BCM"],
  },
  {
    code: "B2477",
    category: "B",
    type: "generic",
    title: "Module Configuration Failure",
    shortDesc: "BCM configuration data is incorrect or corrupted.",
    symptoms: ["Multiple body warnings", "Features disabled"],
    causes: ["Failed programming", "BCM replacement without coding"],
    severity: "moderate",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 100, max: 400 },
    drivable: true,
    affectedSystems: ["BCM"],
  },

  // ─── CHASSIS codes ───
  {
    code: "C0035",
    category: "C",
    type: "generic",
    title: "Left Front Wheel Speed Sensor Circuit",
    shortDesc: "Front-left wheel speed sensor circuit fault.",
    symptoms: ["ABS light on", "Traction control off", "Possible stability control off"],
    causes: ["Bad WSS", "Wiring damage", "Damaged tone ring"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 500 },
    drivable: true,
    affectedSystems: ["ABS", "Traction Control"],
  },
  {
    code: "C0040",
    category: "C",
    type: "generic",
    title: "Right Front Wheel Speed Sensor Circuit",
    shortDesc: "Front-right wheel speed sensor circuit fault.",
    symptoms: ["ABS light", "TC/Stability off"],
    causes: ["Bad WSS", "Wiring", "Tone ring"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 500 },
    drivable: true,
    affectedSystems: ["ABS"],
  },
  {
    code: "C0045",
    category: "C",
    type: "generic",
    title: "Left Rear Wheel Speed Sensor Circuit",
    shortDesc: "Rear-left WSS circuit fault.",
    symptoms: ["ABS light"],
    causes: ["Sensor", "Wiring", "Tone ring"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 500 },
    drivable: true,
    affectedSystems: ["ABS"],
  },
  {
    code: "C0050",
    category: "C",
    type: "generic",
    title: "Right Rear Wheel Speed Sensor Circuit",
    shortDesc: "Rear-right WSS circuit fault.",
    symptoms: ["ABS light"],
    causes: ["Sensor", "Wiring"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 500 },
    drivable: true,
    affectedSystems: ["ABS"],
  },
  {
    code: "C0110",
    category: "C",
    type: "generic",
    title: "ABS Pump Motor Circuit Malfunction",
    shortDesc: "ABS hydraulic pump motor circuit fault.",
    symptoms: ["ABS light", "Loss of ABS function"],
    causes: ["Failed pump motor", "Wiring", "Bad ABS module"],
    severity: "high",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 400, max: 1800 },
    drivable: true,
    affectedSystems: ["ABS"],
  },
  {
    code: "C0145",
    category: "C",
    type: "generic",
    title: "ABS Solenoid Valve Circuit Fault",
    shortDesc: "Internal solenoid in ABS modulator failed.",
    symptoms: ["ABS light", "Hard pedal", "Lockup on hard braking"],
    causes: ["Failed ABS modulator", "Wiring"],
    severity: "high",
    diyDifficulty: "professional",
    estimatedRepairCost: { min: 500, max: 2000 },
    drivable: true,
    affectedSystems: ["ABS"],
  },
  {
    code: "C1145",
    category: "C",
    type: "generic",
    title: "Wheel Speed Sensor Input Signal Fault",
    shortDesc: "ABS module reports invalid input from a wheel speed sensor.",
    symptoms: ["ABS light", "Stability control off"],
    causes: ["Bad WSS", "Wiring", "Loose connector"],
    severity: "moderate",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 150, max: 500 },
    drivable: true,
    affectedSystems: ["ABS", "Traction Control"],
  },

  // ─── NETWORK codes ───
  {
    code: "U0001",
    category: "U",
    type: "generic",
    title: "High Speed CAN Communication Bus",
    shortDesc: "General fault on the high-speed CAN bus.",
    symptoms: ["Multiple module faults", "Multiple warning lights"],
    causes: ["Wiring short", "Failed module", "Bad connector"],
    severity: "high",
    diyDifficulty: "hard",
    estimatedRepairCost: { min: 200, max: 1500 },
    drivable: true,
    affectedSystems: ["CAN Bus", "Communication"],
  },
  {
    code: "U0073",
    category: "U",
    type: "generic",
    title: "Control Module Communication Bus Off",
    shortDesc: "A control module has dropped off the communication bus.",
    symptoms: ["Multiple warning lights", "Loss of features"],
    causes: ["Wiring fault", "Failed module"],
    severity: "high",
    diyDifficulty: "hard",
    estimatedRepairCost: { min: 200, max: 1500 },
    drivable: true,
    affectedSystems: ["CAN Bus"],
  },
  {
    code: "U0100",
    category: "U",
    type: "generic",
    title: "Lost Communication With ECM/PCM 'A'",
    shortDesc: "A module on the bus has lost communication with the engine control module.",
    symptoms: ["Multiple warning lights", "Stalling", "No-start", "Limp mode"],
    causes: ["Bad wiring/connectors", "Failed PCM", "Power/ground issue"],
    severity: "high",
    diyDifficulty: "hard",
    estimatedRepairCost: { min: 100, max: 1500 },
    drivable: false,
    affectedSystems: ["CAN Bus", "PCM"],
  },
  {
    code: "U0101",
    category: "U",
    type: "generic",
    title: "Lost Communication With TCM",
    shortDesc: "Lost CAN communication with the transmission control module.",
    symptoms: ["Limp mode", "Harsh shifts", "Multiple warnings"],
    causes: ["TCM failure", "Wiring fault", "CAN bus issue"],
    severity: "high",
    diyDifficulty: "hard",
    estimatedRepairCost: { min: 200, max: 1800 },
    drivable: true,
    affectedSystems: ["CAN Bus", "Transmission"],
  },
  {
    code: "U0121",
    category: "U",
    type: "generic",
    title: "Lost Communication With ABS Control Module",
    shortDesc: "Lost CAN communication with ABS module.",
    symptoms: ["ABS light", "Stability control off", "Speedometer issues"],
    causes: ["ABS module failure", "Wiring", "CAN issue"],
    severity: "high",
    diyDifficulty: "hard",
    estimatedRepairCost: { min: 200, max: 1500 },
    drivable: true,
    affectedSystems: ["CAN Bus", "ABS"],
  },
  {
    code: "U0140",
    category: "U",
    type: "generic",
    title: "Lost Communication With Body Control Module",
    shortDesc: "BCM is no longer communicating on the network.",
    symptoms: ["Multiple body warnings", "Lights/locks/windows issues"],
    causes: ["BCM failure", "Wiring", "Power/ground"],
    severity: "high",
    diyDifficulty: "hard",
    estimatedRepairCost: { min: 200, max: 1500 },
    drivable: true,
    affectedSystems: ["CAN Bus", "BCM"],
  },
  {
    code: "U0155",
    category: "U",
    type: "generic",
    title: "Lost Communication With Instrument Panel Cluster",
    shortDesc: "Communication with the instrument cluster has been lost.",
    symptoms: ["Dead gauges", "Warning lights stay on or off", "Speedometer non-functional"],
    causes: ["Cluster failure", "Wiring", "Power/ground"],
    severity: "high",
    diyDifficulty: "hard",
    estimatedRepairCost: { min: 200, max: 1500 },
    drivable: true,
    affectedSystems: ["CAN Bus", "Instrument Cluster"],
  },
  {
    code: "U0184",
    category: "U",
    type: "generic",
    title: "Lost Communication With Radio",
    shortDesc: "Communication lost with the audio/infotainment unit.",
    symptoms: ["Radio dead", "No audio", "Backup cam may fail"],
    causes: ["Radio failure", "Wiring", "Fuse"],
    severity: "low",
    diyDifficulty: "moderate",
    estimatedRepairCost: { min: 100, max: 800 },
    drivable: true,
    affectedSystems: ["Infotainment"],
  },
  {
    code: "U0401",
    category: "U",
    type: "generic",
    title: "Invalid Data Received From ECM/PCM",
    shortDesc: "Another module is receiving bad/invalid data from the PCM.",
    symptoms: ["Multiple lights", "Erratic behavior"],
    causes: ["PCM issue", "Wiring", "Software"],
    severity: "high",
    diyDifficulty: "hard",
    estimatedRepairCost: { min: 200, max: 1500 },
    drivable: true,
    affectedSystems: ["CAN Bus", "PCM"],
  },
];

export const TOP_CODES = [
  "P0420",
  "P0171",
  "P0300",
  "P0455",
  "P0700",
  "P0011",
  "P0128",
  "P0140",
  "P0456",
  "P0442",
  "P0301",
  "P0430",
  "P0174",
  "P0172",
  "P0506",
  "P0507",
  "P0335",
  "P0340",
];

export function findCode(input: string): OBD2Code | null {
  if (!input) return null;
  const norm = input.trim().toUpperCase();
  return OBD2_CODES.find((c) => c.code === norm) ?? null;
}

export function searchCodes(query: string): OBD2Code[] {
  const q = query.trim().toUpperCase();
  if (!q) return [];
  return OBD2_CODES.filter(
    (c) =>
      c.code.startsWith(q) ||
      c.code.includes(q) ||
      c.title.toUpperCase().includes(q),
  ).slice(0, 30);
}
