export interface StateInfo {
  slug: string;
  name: string;
  abbr: string;
  dmvName: string;
  titleBrands: string[];
  population: string;
  vehiclesRegistered: string;
  lemonLawNotes: string;
  specialFact: string;
}

export const states: StateInfo[] = [
  { slug: "alabama", name: "Alabama", abbr: "AL", dmvName: "Alabama Department of Revenue Motor Vehicle Division", titleBrands: ["Salvage", "Junk", "Rebuilt", "Flood"], population: "5.1M", vehiclesRegistered: "4.4M", lemonLawNotes: "Alabama's Lemon Law covers new vehicles within 12 months or 12,000 miles, whichever comes first.", specialFact: "Alabama requires a VIN inspection on all out-of-state vehicles before they can be titled in the state." },
  { slug: "alaska", name: "Alaska", abbr: "AK", dmvName: "Alaska Division of Motor Vehicles", titleBrands: ["Salvage", "Reconstructed", "Flood", "Junk"], population: "0.73M", vehiclesRegistered: "0.78M", lemonLawNotes: "Alaska's Lemon Law applies to new vehicles for the first year or warranty period.", specialFact: "Alaska brands titles for vehicles damaged by the harsh subarctic climate and corrosive winter road treatments." },
  { slug: "arizona", name: "Arizona", abbr: "AZ", dmvName: "Arizona Motor Vehicle Division (MVD)", titleBrands: ["Salvage", "Restored Salvage", "Non-Repairable", "Flood"], population: "7.4M", vehiclesRegistered: "5.9M", lemonLawNotes: "Arizona's Lemon Law covers new vehicles within 24 months or 24,000 miles.", specialFact: "Arizona's emissions program means VIN-based emissions history is a key part of any pre-purchase check in Maricopa and Pima counties." },
  { slug: "arkansas", name: "Arkansas", abbr: "AR", dmvName: "Arkansas Department of Finance and Administration", titleBrands: ["Salvage", "Rebuilt", "Prior Salvage", "Flood"], population: "3.0M", vehiclesRegistered: "2.5M", lemonLawNotes: "Arkansas's Lemon Law applies to new vehicles within 24 months or 24,000 miles.", specialFact: "Arkansas requires VIN verification by law enforcement for many used vehicle title transfers." },
  { slug: "california", name: "California", abbr: "CA", dmvName: "California Department of Motor Vehicles (DMV)", titleBrands: ["Salvage", "Non-Repairable", "Revived Salvage", "Flood", "Lemon Law Buyback"], population: "39.5M", vehiclesRegistered: "31M", lemonLawNotes: "California's Song-Beverly Consumer Warranty Act is one of the strongest lemon laws in the nation, offering broad protection to new and used vehicle buyers under warranty.", specialFact: "California uniquely brands titles with 'Lemon Law Buyback' so buyers can identify previously repurchased lemon vehicles." },
  { slug: "colorado", name: "Colorado", abbr: "CO", dmvName: "Colorado Division of Motor Vehicles", titleBrands: ["Salvage", "Rebuilt", "Hail Damage", "Flood"], population: "5.8M", vehiclesRegistered: "5.0M", lemonLawNotes: "Colorado's Lemon Law covers new vehicles within one year of purchase.", specialFact: "Colorado is one of the few states with a 'Hail Damage' title brand reflecting its frequent severe storms." },
  { slug: "connecticut", name: "Connecticut", abbr: "CT", dmvName: "Connecticut Department of Motor Vehicles", titleBrands: ["Salvage", "Salvage Parts Only", "Rebuilt", "Flood"], population: "3.6M", vehiclesRegistered: "2.8M", lemonLawNotes: "Connecticut enacted the nation's first lemon law in 1982, covering new vehicles within 24 months or 24,000 miles.", specialFact: "Connecticut's Lemon Law was the first of its kind in the United States and remains a national model." },
  { slug: "delaware", name: "Delaware", abbr: "DE", dmvName: "Delaware Division of Motor Vehicles", titleBrands: ["Salvage", "Rebuilt", "Distressed", "Flood"], population: "1.0M", vehiclesRegistered: "0.94M", lemonLawNotes: "Delaware's Lemon Law applies to new vehicles within 12 months of delivery.", specialFact: "Delaware uses a 'Distressed' brand to flag vehicles with significant non-collision damage." },
  { slug: "florida", name: "Florida", abbr: "FL", dmvName: "Florida Department of Highway Safety and Motor Vehicles", titleBrands: ["Salvage", "Rebuilt", "Certificate of Destruction", "Flood", "Hurricane"], population: "22.6M", vehiclesRegistered: "17.5M", lemonLawNotes: "Florida's Lemon Law covers new and demonstrator vehicles within 24 months from delivery.", specialFact: "Florida has the highest rate of flood-damaged vehicles re-entering the market due to recurring hurricanes." },
  { slug: "georgia", name: "Georgia", abbr: "GA", dmvName: "Georgia Department of Revenue Motor Vehicle Division", titleBrands: ["Salvage", "Rebuilt", "Unrebuildable", "Flood"], population: "11.0M", vehiclesRegistered: "8.3M", lemonLawNotes: "Georgia's Lemon Law covers new vehicles within 24 months or 24,000 miles.", specialFact: "Georgia issues an 'Unrebuildable' designation for vehicles too damaged to ever be re-titled for road use." },
  { slug: "hawaii", name: "Hawaii", abbr: "HI", dmvName: "Hawaii Department of Customer Services", titleBrands: ["Salvage", "Reconstructed", "Flood", "Total Loss"], population: "1.4M", vehiclesRegistered: "1.2M", lemonLawNotes: "Hawaii's Lemon Law covers new vehicles within 24 months, 24,000 miles, or warranty term.", specialFact: "Hawaii's salt-air corrosion is a key reason VIN-based history checks should always include past registration locations." },
  { slug: "idaho", name: "Idaho", abbr: "ID", dmvName: "Idaho Transportation Department", titleBrands: ["Salvage", "Rebuilt", "Junk", "Flood"], population: "2.0M", vehiclesRegistered: "1.8M", lemonLawNotes: "Idaho's Lemon Law applies within 24 months or 24,000 miles for new vehicles.", specialFact: "Idaho requires VIN inspection by an authorized agency for any out-of-state vehicle being titled." },
  { slug: "illinois", name: "Illinois", abbr: "IL", dmvName: "Illinois Secretary of State Vehicle Services", titleBrands: ["Salvage", "Rebuilt", "Junk", "Flood"], population: "12.5M", vehiclesRegistered: "10.7M", lemonLawNotes: "Illinois's New Vehicle Buyer Protection Act covers vehicles within 12 months or 12,000 miles.", specialFact: "Illinois law makes it a felony to alter a VIN, and the Secretary of State actively investigates VIN tampering." },
  { slug: "indiana", name: "Indiana", abbr: "IN", dmvName: "Indiana Bureau of Motor Vehicles", titleBrands: ["Salvage", "Rebuilt", "Disclosed Damage", "Flood"], population: "6.8M", vehiclesRegistered: "5.7M", lemonLawNotes: "Indiana's Lemon Law covers new vehicles within 18 months or 18,000 miles.", specialFact: "Indiana uses a 'Disclosed Damage' brand to flag vehicles with significant past damage that may not meet salvage thresholds." },
  { slug: "iowa", name: "Iowa", abbr: "IA", dmvName: "Iowa Department of Transportation", titleBrands: ["Salvage", "Prior Salvage", "Rebuilt", "Flood"], population: "3.2M", vehiclesRegistered: "3.6M", lemonLawNotes: "Iowa's Lemon Law applies to new vehicles within two years or 24,000 miles.", specialFact: "Iowa law requires that flood-damaged vehicles be permanently branded on the title to protect future buyers." },
  { slug: "kansas", name: "Kansas", abbr: "KS", dmvName: "Kansas Department of Revenue Division of Vehicles", titleBrands: ["Salvage", "Rebuilt", "Non-Highway", "Flood"], population: "3.0M", vehiclesRegistered: "2.7M", lemonLawNotes: "Kansas's Lemon Law applies within one year of delivery for new vehicles.", specialFact: "Kansas uses a 'Non-Highway' brand for vehicles that cannot legally be operated on public roads." },
  { slug: "kentucky", name: "Kentucky", abbr: "KY", dmvName: "Kentucky Transportation Cabinet", titleBrands: ["Salvage", "Rebuilt", "Junked", "Flood"], population: "4.5M", vehiclesRegistered: "3.8M", lemonLawNotes: "Kentucky's Lemon Law covers new motor vehicles within 12 months or 12,000 miles.", specialFact: "Kentucky requires a VIN inspection by the State Police for many salvage and rebuilt title applications." },
  { slug: "louisiana", name: "Louisiana", abbr: "LA", dmvName: "Louisiana Office of Motor Vehicles", titleBrands: ["Salvage", "Rebuilt", "Flood", "Hurricane"], population: "4.6M", vehiclesRegistered: "3.9M", lemonLawNotes: "Louisiana's Lemon Law covers new vehicles within one year of delivery.", specialFact: "Louisiana brands titles for hurricane and flood-damaged vehicles, a critical check given the state's storm exposure." },
  { slug: "maine", name: "Maine", abbr: "ME", dmvName: "Maine Bureau of Motor Vehicles", titleBrands: ["Salvage", "Rebuilt", "Flood", "Junk"], population: "1.4M", vehiclesRegistered: "1.1M", lemonLawNotes: "Maine's Lemon Law covers new vehicles for three years or 18,000 miles.", specialFact: "Maine titles vehicles older than 1995 with a registration only, making VIN history especially important for older trucks." },
  { slug: "maryland", name: "Maryland", abbr: "MD", dmvName: "Maryland Motor Vehicle Administration", titleBrands: ["Salvage", "Rebuilt", "Flood", "Non-Repairable"], population: "6.2M", vehiclesRegistered: "4.4M", lemonLawNotes: "Maryland's Lemon Law applies to new vehicles within 24 months or 18,000 miles.", specialFact: "Maryland requires a state safety inspection for every used vehicle title transfer, with VIN verification included." },
  { slug: "massachusetts", name: "Massachusetts", abbr: "MA", dmvName: "Massachusetts Registry of Motor Vehicles", titleBrands: ["Salvage", "Reconstructed", "Owner Retained", "Flood"], population: "7.0M", vehiclesRegistered: "5.5M", lemonLawNotes: "Massachusetts has both a New Car Lemon Law and a Used Vehicle Lemon Law, providing some of the strongest used-car protections in the U.S.", specialFact: "Massachusetts is one of the few states with a Used Vehicle Lemon Law applying to dealer-sold cars under 125,000 miles." },
  { slug: "michigan", name: "Michigan", abbr: "MI", dmvName: "Michigan Secretary of State", titleBrands: ["Salvage", "Rebuilt Salvage", "Scrap", "Flood"], population: "10.0M", vehiclesRegistered: "8.0M", lemonLawNotes: "Michigan's Lemon Law covers new vehicles within the first year or warranty term.", specialFact: "As home of the Big Three automakers, Michigan VIN records are extensive and tied closely to manufacturer recall data." },
  { slug: "minnesota", name: "Minnesota", abbr: "MN", dmvName: "Minnesota Driver and Vehicle Services", titleBrands: ["Salvage", "Prior Salvage", "Rebuilt", "Flood"], population: "5.7M", vehiclesRegistered: "5.1M", lemonLawNotes: "Minnesota's Lemon Law covers new vehicles within two years or warranty period.", specialFact: "Minnesota's harsh winters and road salt make rust and undercarriage history particularly important when checking a VIN." },
  { slug: "mississippi", name: "Mississippi", abbr: "MS", dmvName: "Mississippi Department of Revenue", titleBrands: ["Salvage", "Rebuilt", "Flood", "Junk"], population: "2.9M", vehiclesRegistered: "2.0M", lemonLawNotes: "Mississippi's Lemon Law applies to new vehicles within 12 months or 12,000 miles.", specialFact: "Mississippi has historically been a destination for flood-damaged vehicles from Gulf Coast hurricanes, making VIN checks essential." },
  { slug: "missouri", name: "Missouri", abbr: "MO", dmvName: "Missouri Department of Revenue", titleBrands: ["Salvage", "Prior Salvage", "Junking Certificate", "Flood"], population: "6.2M", vehiclesRegistered: "5.0M", lemonLawNotes: "Missouri's Lemon Law covers new vehicles within one year or warranty term.", specialFact: "Missouri requires a vehicle examination by the Missouri State Highway Patrol for prior salvage vehicles before they can be re-titled." },
  { slug: "montana", name: "Montana", abbr: "MT", dmvName: "Montana Motor Vehicle Division", titleBrands: ["Salvage", "Rebuilt", "Junk", "Flood"], population: "1.1M", vehiclesRegistered: "1.5M", lemonLawNotes: "Montana's Lemon Law covers new vehicles within two years or warranty period.", specialFact: "Montana's lack of vehicle sales tax has made it a popular state for LLC registrations, so VIN history may show out-of-state usage." },
  { slug: "nebraska", name: "Nebraska", abbr: "NE", dmvName: "Nebraska Department of Motor Vehicles", titleBrands: ["Salvage", "Previous Salvage", "Junk", "Flood"], population: "2.0M", vehiclesRegistered: "1.9M", lemonLawNotes: "Nebraska's Lemon Law applies to new vehicles within one year or warranty term.", specialFact: "Nebraska brands titles for vehicles assembled from used parts, helping buyers identify rebuilt cars." },
  { slug: "nevada", name: "Nevada", abbr: "NV", dmvName: "Nevada Department of Motor Vehicles", titleBrands: ["Salvage", "Rebuilt", "Non-Repairable", "Flood"], population: "3.2M", vehiclesRegistered: "2.5M", lemonLawNotes: "Nevada's Lemon Law covers new vehicles within one year or warranty term.", specialFact: "Nevada requires a VIN inspection by DMV personnel for any out-of-state vehicle before it can be registered." },
  { slug: "new-hampshire", name: "New Hampshire", abbr: "NH", dmvName: "New Hampshire Division of Motor Vehicles", titleBrands: ["Salvage", "Rebuilt", "Parts Only", "Flood"], population: "1.4M", vehiclesRegistered: "1.4M", lemonLawNotes: "New Hampshire's Lemon Law applies to new vehicles within the warranty term.", specialFact: "New Hampshire only titles vehicles 2000 model year or newer, making VIN-based history reports vital for older vehicles." },
  { slug: "new-jersey", name: "New Jersey", abbr: "NJ", dmvName: "New Jersey Motor Vehicle Commission", titleBrands: ["Salvage", "Reconstructed", "Flood", "Non-Repairable"], population: "9.3M", vehiclesRegistered: "6.4M", lemonLawNotes: "New Jersey's Lemon Law covers new vehicles within 24 months or 24,000 miles.", specialFact: "New Jersey's Used Car Lemon Law also covers dealer-sold used vehicles, a rare consumer protection nationwide." },
  { slug: "new-mexico", name: "New Mexico", abbr: "NM", dmvName: "New Mexico Motor Vehicle Division", titleBrands: ["Salvage", "Rebuilt", "Flood", "Non-Repairable"], population: "2.1M", vehiclesRegistered: "1.9M", lemonLawNotes: "New Mexico's Lemon Law covers new vehicles within one year or warranty term.", specialFact: "New Mexico requires VIN inspection at a port of entry for vehicles imported from Mexico." },
  { slug: "new-york", name: "New York", abbr: "NY", dmvName: "New York State Department of Motor Vehicles", titleBrands: ["Salvage", "Rebuilt Salvage", "Non-Rebuildable", "Flood"], population: "19.5M", vehiclesRegistered: "11.7M", lemonLawNotes: "New York has both a New Car and Used Car Lemon Law providing comprehensive consumer protection.", specialFact: "New York requires a DMV anti-theft examination before any rebuilt salvage vehicle can be titled and registered." },
  { slug: "north-carolina", name: "North Carolina", abbr: "NC", dmvName: "North Carolina Division of Motor Vehicles", titleBrands: ["Salvage", "Reconstructed", "Flood", "Junk"], population: "10.7M", vehiclesRegistered: "8.5M", lemonLawNotes: "North Carolina's Lemon Law covers new vehicles within 24 months, 24,000 miles, or the warranty term.", specialFact: "North Carolina requires that any vehicle damaged 75% or more of fair market value receive a salvage title." },
  { slug: "north-dakota", name: "North Dakota", abbr: "ND", dmvName: "North Dakota Department of Transportation", titleBrands: ["Salvage", "Rebuilt", "Junk", "Flood"], population: "0.78M", vehiclesRegistered: "0.94M", lemonLawNotes: "North Dakota's Lemon Law applies to new vehicles within one year or warranty period.", specialFact: "North Dakota's oil-field activity makes truck VIN history especially important for verifying heavy commercial use." },
  { slug: "ohio", name: "Ohio", abbr: "OH", dmvName: "Ohio Bureau of Motor Vehicles", titleBrands: ["Salvage", "Rebuilt Salvage", "Junk", "Flood"], population: "11.8M", vehiclesRegistered: "9.5M", lemonLawNotes: "Ohio's Lemon Law covers new vehicles within one year or 18,000 miles.", specialFact: "Ohio uses a Salvage Inspection program where rebuilt vehicles must pass a State Highway Patrol inspection." },
  { slug: "oklahoma", name: "Oklahoma", abbr: "OK", dmvName: "Oklahoma Service Oklahoma (Service OK)", titleBrands: ["Salvage", "Rebuilt", "Junked", "Flood"], population: "4.0M", vehiclesRegistered: "3.5M", lemonLawNotes: "Oklahoma's Lemon Law covers new vehicles within one year or warranty period.", specialFact: "Oklahoma's frequent severe weather, including tornadoes and hail, makes title brand history a vital VIN check item." },
  { slug: "oregon", name: "Oregon", abbr: "OR", dmvName: "Oregon Driver and Motor Vehicle Services", titleBrands: ["Salvage", "Reconstructed", "Totaled", "Flood"], population: "4.2M", vehiclesRegistered: "3.5M", lemonLawNotes: "Oregon's Lemon Law covers new vehicles within 24 months or 24,000 miles.", specialFact: "Oregon brands titles 'Totaled' for any insurance-declared total loss, providing clear visibility into prior damage." },
  { slug: "pennsylvania", name: "Pennsylvania", abbr: "PA", dmvName: "Pennsylvania Department of Transportation (PennDOT)", titleBrands: ["Salvage", "Reconstructed", "Flood", "Non-Repairable"], population: "13.0M", vehiclesRegistered: "10.5M", lemonLawNotes: "Pennsylvania's Lemon Law covers new vehicles within one year, 12,000 miles, or warranty term.", specialFact: "Pennsylvania requires an enhanced inspection by an authorized agent for any reconstructed vehicle before re-titling." },
  { slug: "rhode-island", name: "Rhode Island", abbr: "RI", dmvName: "Rhode Island Division of Motor Vehicles", titleBrands: ["Salvage", "Reconstructed", "Flood", "Junk"], population: "1.1M", vehiclesRegistered: "0.83M", lemonLawNotes: "Rhode Island's Lemon Law applies to new vehicles within one year or 15,000 miles.", specialFact: "Rhode Island also operates a Used Car Lemon Law covering dealer-sold vehicles, expanding buyer protections." },
  { slug: "south-carolina", name: "South Carolina", abbr: "SC", dmvName: "South Carolina Department of Motor Vehicles", titleBrands: ["Salvage", "Rebuilt", "Flood", "Distressed"], population: "5.4M", vehiclesRegistered: "4.5M", lemonLawNotes: "South Carolina's Lemon Law covers new vehicles within one year or 12,000 miles.", specialFact: "South Carolina requires VIN verification by a law enforcement officer for many out-of-state vehicle title applications." },
  { slug: "south-dakota", name: "South Dakota", abbr: "SD", dmvName: "South Dakota Motor Vehicle Division", titleBrands: ["Salvage", "Rebuilt", "Junk", "Flood"], population: "0.92M", vehiclesRegistered: "1.1M", lemonLawNotes: "South Dakota's Lemon Law applies to new vehicles within one year of purchase.", specialFact: "South Dakota only titles vehicles model year 1976 or newer, so older vehicles often rely solely on VIN history reports." },
  { slug: "tennessee", name: "Tennessee", abbr: "TN", dmvName: "Tennessee Department of Revenue Vehicle Services", titleBrands: ["Salvage", "Rebuilt", "Flood", "Non-Repairable"], population: "7.1M", vehiclesRegistered: "5.5M", lemonLawNotes: "Tennessee's Lemon Law covers new vehicles within one year or warranty period.", specialFact: "Tennessee is home to large Nissan, Volkswagen, and GM plants, making it a hotspot for original-build VIN data." },
  { slug: "texas", name: "Texas", abbr: "TX", dmvName: "Texas Department of Motor Vehicles", titleBrands: ["Salvage", "Rebuilt Salvage", "Flood Damage", "Non-Repairable", "Hail Damage"], population: "30.5M", vehiclesRegistered: "23.5M", lemonLawNotes: "Texas's Lemon Law covers new vehicles within 24 months or 24,000 miles, administered by the Texas DMV.", specialFact: "Texas issues a separate 'Flood Damage' title brand for vehicles flooded by storms or hurricanes, including Hurricane Harvey-affected cars." },
  { slug: "utah", name: "Utah", abbr: "UT", dmvName: "Utah Division of Motor Vehicles", titleBrands: ["Salvage", "Rebuilt", "Non-Repairable", "Flood"], population: "3.4M", vehiclesRegistered: "2.7M", lemonLawNotes: "Utah's Lemon Law covers new vehicles within one year or warranty period.", specialFact: "Utah requires a State Tax Commission inspection for all rebuilt salvage vehicles before they can be re-titled." },
  { slug: "vermont", name: "Vermont", abbr: "VT", dmvName: "Vermont Department of Motor Vehicles", titleBrands: ["Salvage", "Rebuilt", "Flood", "Junk"], population: "0.65M", vehiclesRegistered: "0.62M", lemonLawNotes: "Vermont's Lemon Law covers new vehicles within the manufacturer's warranty period.", specialFact: "Vermont only titles vehicles 15 years old or newer; older vehicles use registration only, making VIN history critical." },
  { slug: "virginia", name: "Virginia", abbr: "VA", dmvName: "Virginia Department of Motor Vehicles", titleBrands: ["Salvage", "Rebuilt", "Non-Repairable", "Flood"], population: "8.7M", vehiclesRegistered: "7.5M", lemonLawNotes: "Virginia's Motor Vehicle Warranty Enforcement Act applies to new vehicles within 18 months.", specialFact: "Virginia requires a state police safety inspection for any rebuilt salvage vehicle before re-titling." },
  { slug: "washington", name: "Washington", abbr: "WA", dmvName: "Washington Department of Licensing", titleBrands: ["Salvage", "Rebuilt", "Destroyed", "Flood"], population: "7.8M", vehiclesRegistered: "6.6M", lemonLawNotes: "Washington's Lemon Law covers new vehicles within 24 months or 24,000 miles.", specialFact: "Washington brands a vehicle 'Destroyed' when it cannot be returned to roadworthy condition, providing strong buyer warnings." },
  { slug: "west-virginia", name: "West Virginia", abbr: "WV", dmvName: "West Virginia Division of Motor Vehicles", titleBrands: ["Salvage", "Reconstructed", "Flood", "Junk"], population: "1.8M", vehiclesRegistered: "1.5M", lemonLawNotes: "West Virginia's Lemon Law covers new vehicles within one year or warranty term.", specialFact: "West Virginia's mountainous terrain and salt-treated roads make undercarriage VIN history particularly relevant." },
  { slug: "wisconsin", name: "Wisconsin", abbr: "WI", dmvName: "Wisconsin Division of Motor Vehicles", titleBrands: ["Salvage", "Junk", "Rebuilt", "Flood"], population: "5.9M", vehiclesRegistered: "5.3M", lemonLawNotes: "Wisconsin's Lemon Law is one of the strongest in the nation, covering new vehicles within one year or warranty term.", specialFact: "Wisconsin's lemon law allows for double damages plus attorney fees, making it a model for consumer protection." },
  { slug: "wyoming", name: "Wyoming", abbr: "WY", dmvName: "Wyoming Department of Transportation", titleBrands: ["Salvage", "Rebuilt", "Junk", "Flood"], population: "0.58M", vehiclesRegistered: "0.78M", lemonLawNotes: "Wyoming's Lemon Law applies to new vehicles within one year or warranty term.", specialFact: "Wyoming's high per-capita vehicle registration reflects rural life and heavy truck use, making VIN-based usage history important." },
];

export function getStateBySlug(slug: string): StateInfo | undefined {
  return states.find((s) => s.slug === slug);
}
