/**
 * Static specs database for the /compare-cars tool.
 *
 * ~40 popular 2024 model-year vehicles. Numbers are realistic estimates
 * sourced from manufacturer pages, EPA fueleconomy.gov, and NHTSA at the
 * time of writing. Reliability and resale scores are subjective 1–10
 * ratings drawn from typical industry-wide consumer-report style data.
 */

export type BodyStyle =
  | "Sedan"
  | "SUV"
  | "Truck"
  | "Hatchback"
  | "Coupe"
  | "Minivan"
  | "Wagon"
  | "Convertible";

export type FuelType =
  | "Gasoline"
  | "Hybrid"
  | "Plug-in Hybrid"
  | "Electric"
  | "Diesel";

export type Drivetrain = "FWD" | "RWD" | "AWD" | "4WD";

export interface VehicleSpec {
  make: string;
  model: string;
  year: number;
  bodyStyle: BodyStyle;
  msrpStart: number;
  msrpEnd: number;
  mpgCity: number;
  mpgHwy: number;
  mpgCombined: number;
  fuelType: FuelType;
  rangeMiles?: number;
  horsepower: number;
  torque: number;
  engine: string;
  transmission: string;
  drivetrain: Drivetrain;
  seatingCapacity: number;
  cargoFt3: number;
  towingLbs: number;
  zeroToSixty: number;
  topSpeed?: number;
  warranty: { basic: string; powertrain: string };
  reliabilityScore: number;
  resaleScore: number;
  safetyScore: number;
  features: string[];
}

export const vehicleSpecs: VehicleSpec[] = [
  // ── Toyota ────────────────────────────────────────────────────────
  {
    make: "Toyota",
    model: "Camry",
    year: 2024,
    bodyStyle: "Sedan",
    msrpStart: 26420,
    msrpEnd: 36945,
    mpgCity: 28,
    mpgHwy: 39,
    mpgCombined: 32,
    fuelType: "Gasoline",
    horsepower: 203,
    torque: 184,
    engine: "2.5L I4",
    transmission: "8-Speed Auto",
    drivetrain: "FWD",
    seatingCapacity: 5,
    cargoFt3: 15.1,
    towingLbs: 1000,
    zeroToSixty: 7.6,
    topSpeed: 135,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 9,
    resaleScore: 9,
    safetyScore: 5,
    features: [
      "Toyota Safety Sense 2.5+",
      "Adaptive Cruise Control",
      "Lane Departure Alert",
      "Apple CarPlay & Android Auto",
      "Wireless Phone Charging",
      "9-inch Touchscreen",
      "Blind Spot Monitor",
      "LED Headlights",
    ],
  },
  {
    make: "Toyota",
    model: "Corolla",
    year: 2024,
    bodyStyle: "Sedan",
    msrpStart: 22050,
    msrpEnd: 28810,
    mpgCity: 32,
    mpgHwy: 41,
    mpgCombined: 35,
    fuelType: "Gasoline",
    horsepower: 169,
    torque: 151,
    engine: "2.0L I4",
    transmission: "CVT",
    drivetrain: "FWD",
    seatingCapacity: 5,
    cargoFt3: 13.1,
    towingLbs: 0,
    zeroToSixty: 7.9,
    topSpeed: 121,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 9,
    resaleScore: 9,
    safetyScore: 5,
    features: [
      "Toyota Safety Sense 3.0",
      "Pre-Collision System",
      "Lane Tracing Assist",
      "8-inch Touchscreen",
      "Apple CarPlay & Android Auto",
      "LED Headlights",
      "Automatic Climate Control",
      "Smart Key Entry",
    ],
  },
  {
    make: "Toyota",
    model: "RAV4",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 28675,
    msrpEnd: 38875,
    mpgCity: 27,
    mpgHwy: 35,
    mpgCombined: 30,
    fuelType: "Gasoline",
    horsepower: 203,
    torque: 184,
    engine: "2.5L I4",
    transmission: "8-Speed Auto",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 37.6,
    towingLbs: 1500,
    zeroToSixty: 8.0,
    topSpeed: 118,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 9,
    resaleScore: 10,
    safetyScore: 5,
    features: [
      "Toyota Safety Sense 2.5",
      "Standard AWD Available",
      "Power Liftgate",
      "Heated Front Seats",
      "Apple CarPlay & Android Auto",
      "Roof Rails",
      "Blind Spot Monitor",
      "Wi-Fi Connect",
    ],
  },
  {
    make: "Toyota",
    model: "Highlander",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 39270,
    msrpEnd: 53580,
    mpgCity: 22,
    mpgHwy: 29,
    mpgCombined: 25,
    fuelType: "Gasoline",
    horsepower: 265,
    torque: 309,
    engine: "2.4L Turbo I4",
    transmission: "8-Speed Auto",
    drivetrain: "AWD",
    seatingCapacity: 8,
    cargoFt3: 16.0,
    towingLbs: 5000,
    zeroToSixty: 7.2,
    topSpeed: 130,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 9,
    resaleScore: 9,
    safetyScore: 5,
    features: [
      "3-Row Seating",
      "Toyota Safety Sense 2.5+",
      "12.3-inch Touchscreen",
      "Panoramic Moonroof",
      "Tri-Zone Climate Control",
      "JBL Premium Audio",
      "Hands-Free Liftgate",
      "Heated & Ventilated Seats",
    ],
  },
  {
    make: "Toyota",
    model: "Tacoma",
    year: 2024,
    bodyStyle: "Truck",
    msrpStart: 31500,
    msrpEnd: 53595,
    mpgCity: 21,
    mpgHwy: 26,
    mpgCombined: 23,
    fuelType: "Gasoline",
    horsepower: 278,
    torque: 317,
    engine: "2.4L Turbo I4",
    transmission: "8-Speed Auto",
    drivetrain: "4WD",
    seatingCapacity: 5,
    cargoFt3: 0,
    towingLbs: 6500,
    zeroToSixty: 7.0,
    topSpeed: 115,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 9,
    resaleScore: 10,
    safetyScore: 4,
    features: [
      "Toyota Safety Sense 3.0",
      "Multi-Terrain Select",
      "Crawl Control",
      "Locking Rear Differential",
      "Skid Plates",
      "8-inch Touchscreen",
      "Apple CarPlay & Android Auto",
      "Trail-Tuned Suspension",
    ],
  },
  {
    make: "Toyota",
    model: "Tundra",
    year: 2024,
    bodyStyle: "Truck",
    msrpStart: 39965,
    msrpEnd: 78380,
    mpgCity: 18,
    mpgHwy: 24,
    mpgCombined: 20,
    fuelType: "Gasoline",
    horsepower: 389,
    torque: 479,
    engine: "3.5L Twin-Turbo V6",
    transmission: "10-Speed Auto",
    drivetrain: "4WD",
    seatingCapacity: 6,
    cargoFt3: 0,
    towingLbs: 12000,
    zeroToSixty: 6.1,
    topSpeed: 130,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 8,
    resaleScore: 9,
    safetyScore: 4,
    features: [
      "Toyota Safety Sense 2.5",
      "14-inch Touchscreen",
      "Trailer Backup Guide",
      "Panoramic View Monitor",
      "Tow/Haul Mode",
      "JBL Premium Audio",
      "Tow Hitch Receiver",
      "Power Tailgate",
    ],
  },
  {
    make: "Toyota",
    model: "Prius",
    year: 2024,
    bodyStyle: "Hatchback",
    msrpStart: 27950,
    msrpEnd: 35865,
    mpgCity: 57,
    mpgHwy: 56,
    mpgCombined: 57,
    fuelType: "Hybrid",
    horsepower: 196,
    torque: 139,
    engine: "2.0L I4 Hybrid",
    transmission: "CVT",
    drivetrain: "FWD",
    seatingCapacity: 5,
    cargoFt3: 23.8,
    towingLbs: 0,
    zeroToSixty: 7.1,
    topSpeed: 115,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 9,
    resaleScore: 9,
    safetyScore: 5,
    features: [
      "Toyota Safety Sense 3.0",
      "Hybrid Synergy Drive",
      "8-inch Touchscreen",
      "Wireless Apple CarPlay",
      "LED Headlights",
      "Available Solar Roof",
      "Heated Steering Wheel",
      "Adaptive Cruise Control",
    ],
  },

  // ── Honda ─────────────────────────────────────────────────────────
  {
    make: "Honda",
    model: "Civic",
    year: 2024,
    bodyStyle: "Sedan",
    msrpStart: 23950,
    msrpEnd: 31900,
    mpgCity: 31,
    mpgHwy: 40,
    mpgCombined: 35,
    fuelType: "Gasoline",
    horsepower: 158,
    torque: 138,
    engine: "2.0L I4",
    transmission: "CVT",
    drivetrain: "FWD",
    seatingCapacity: 5,
    cargoFt3: 14.8,
    towingLbs: 0,
    zeroToSixty: 8.2,
    topSpeed: 125,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 9,
    resaleScore: 9,
    safetyScore: 5,
    features: [
      "Honda Sensing Suite",
      "Collision Mitigation Braking",
      "Adaptive Cruise Control",
      "Apple CarPlay & Android Auto",
      "9-inch Touchscreen",
      "Wireless Charging",
      "Heated Front Seats",
      "Bose Premium Audio",
    ],
  },
  {
    make: "Honda",
    model: "Accord",
    year: 2024,
    bodyStyle: "Sedan",
    msrpStart: 27895,
    msrpEnd: 38985,
    mpgCity: 29,
    mpgHwy: 37,
    mpgCombined: 32,
    fuelType: "Gasoline",
    horsepower: 192,
    torque: 192,
    engine: "1.5L Turbo I4",
    transmission: "CVT",
    drivetrain: "FWD",
    seatingCapacity: 5,
    cargoFt3: 16.7,
    towingLbs: 1000,
    zeroToSixty: 7.2,
    topSpeed: 130,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 9,
    resaleScore: 8,
    safetyScore: 5,
    features: [
      "Honda Sensing 360",
      "12.3-inch Touchscreen",
      "Google Built-In",
      "Wireless Apple CarPlay",
      "Heated Front & Rear Seats",
      "Head-Up Display",
      "Bose Premium Audio",
      "Power Moonroof",
    ],
  },
  {
    make: "Honda",
    model: "CR-V",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 29500,
    msrpEnd: 40050,
    mpgCity: 28,
    mpgHwy: 34,
    mpgCombined: 30,
    fuelType: "Gasoline",
    horsepower: 190,
    torque: 179,
    engine: "1.5L Turbo I4",
    transmission: "CVT",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 39.3,
    towingLbs: 1500,
    zeroToSixty: 8.0,
    topSpeed: 120,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 9,
    resaleScore: 9,
    safetyScore: 5,
    features: [
      "Honda Sensing Suite",
      "Real-Time AWD",
      "Power Liftgate",
      "Apple CarPlay & Android Auto",
      "Heated Seats",
      "Panoramic Moonroof",
      "Bose Premium Audio",
      "Hands-Free Tailgate",
    ],
  },
  {
    make: "Honda",
    model: "Pilot",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 40150,
    msrpEnd: 54180,
    mpgCity: 19,
    mpgHwy: 27,
    mpgCombined: 22,
    fuelType: "Gasoline",
    horsepower: 285,
    torque: 262,
    engine: "3.5L V6",
    transmission: "10-Speed Auto",
    drivetrain: "AWD",
    seatingCapacity: 8,
    cargoFt3: 18.6,
    towingLbs: 5000,
    zeroToSixty: 7.0,
    topSpeed: 130,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 8,
    resaleScore: 8,
    safetyScore: 5,
    features: [
      "3-Row Seating",
      "Honda Sensing Suite",
      "9-inch Touchscreen",
      "TrailWatch Camera System",
      "Tri-Zone Climate Control",
      "Wireless Apple CarPlay",
      "Hands-Free Power Tailgate",
      "Bose 12-Speaker Audio",
    ],
  },
  {
    make: "Honda",
    model: "HR-V",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 24600,
    msrpEnd: 30650,
    mpgCity: 26,
    mpgHwy: 32,
    mpgCombined: 28,
    fuelType: "Gasoline",
    horsepower: 158,
    torque: 138,
    engine: "2.0L I4",
    transmission: "CVT",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 24.4,
    towingLbs: 0,
    zeroToSixty: 9.4,
    topSpeed: 115,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 8,
    resaleScore: 8,
    safetyScore: 5,
    features: [
      "Honda Sensing Suite",
      "Real-Time AWD",
      "7-inch Touchscreen",
      "Apple CarPlay & Android Auto",
      "60/40 Split Rear Seat",
      "Magic Seat Configurations",
      "Heated Front Seats",
      "LED Headlights",
    ],
  },

  // ── Ford ──────────────────────────────────────────────────────────
  {
    make: "Ford",
    model: "F-150",
    year: 2024,
    bodyStyle: "Truck",
    msrpStart: 36965,
    msrpEnd: 84130,
    mpgCity: 19,
    mpgHwy: 24,
    mpgCombined: 21,
    fuelType: "Gasoline",
    horsepower: 400,
    torque: 410,
    engine: "3.5L Twin-Turbo V6",
    transmission: "10-Speed Auto",
    drivetrain: "4WD",
    seatingCapacity: 6,
    cargoFt3: 0,
    towingLbs: 13500,
    zeroToSixty: 5.7,
    topSpeed: 107,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 7,
    resaleScore: 9,
    safetyScore: 5,
    features: [
      "Pro Power Onboard Generator",
      "BlueCruise Hands-Free Driving",
      "12-inch Touchscreen",
      "Tailgate Work Surface",
      "Pro Trailer Backup Assist",
      "Onboard Scales",
      "B&O Premium Audio",
      "360-Degree Camera",
    ],
  },
  {
    make: "Ford",
    model: "Mustang",
    year: 2024,
    bodyStyle: "Coupe",
    msrpStart: 30920,
    msrpEnd: 65495,
    mpgCity: 22,
    mpgHwy: 33,
    mpgCombined: 26,
    fuelType: "Gasoline",
    horsepower: 315,
    torque: 350,
    engine: "2.3L EcoBoost I4",
    transmission: "10-Speed Auto",
    drivetrain: "RWD",
    seatingCapacity: 4,
    cargoFt3: 13.5,
    towingLbs: 0,
    zeroToSixty: 5.2,
    topSpeed: 145,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 7,
    resaleScore: 8,
    safetyScore: 4,
    features: [
      "13.2-inch Touchscreen",
      "Selectable Drive Modes",
      "Active Performance Exhaust",
      "Recaro Sport Seats Available",
      "Brembo Performance Brakes",
      "Track Apps Performance Suite",
      "Apple CarPlay & Android Auto",
      "B&O Premium Audio",
    ],
  },
  {
    make: "Ford",
    model: "Bronco",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 39185,
    msrpEnd: 64970,
    mpgCity: 17,
    mpgHwy: 17,
    mpgCombined: 17,
    fuelType: "Gasoline",
    horsepower: 300,
    torque: 325,
    engine: "2.7L EcoBoost V6",
    transmission: "10-Speed Auto",
    drivetrain: "4WD",
    seatingCapacity: 5,
    cargoFt3: 35.6,
    towingLbs: 3500,
    zeroToSixty: 6.7,
    topSpeed: 110,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 6,
    resaleScore: 9,
    safetyScore: 4,
    features: [
      "G.O.A.T. Modes (7 terrain modes)",
      "Removable Doors & Roof",
      "Electronic Locking Differentials",
      "Trail Turn Assist",
      "Trail Control Cruise",
      "12-inch Touchscreen",
      "B&O Premium Audio",
      "Sasquatch Off-Road Package",
    ],
  },
  {
    make: "Ford",
    model: "Escape",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 28000,
    msrpEnd: 38390,
    mpgCity: 27,
    mpgHwy: 34,
    mpgCombined: 30,
    fuelType: "Gasoline",
    horsepower: 180,
    torque: 199,
    engine: "1.5L EcoBoost I3",
    transmission: "8-Speed Auto",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 37.5,
    towingLbs: 2000,
    zeroToSixty: 8.6,
    topSpeed: 117,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 7,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "Ford Co-Pilot360 Suite",
      "13.2-inch Touchscreen",
      "Wireless Apple CarPlay",
      "B&O Premium Audio",
      "Sliding Rear Seat",
      "Hands-Free Power Liftgate",
      "Heated Front Seats",
      "Wireless Charging Pad",
    ],
  },
  {
    make: "Ford",
    model: "Explorer",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 38455,
    msrpEnd: 58530,
    mpgCity: 21,
    mpgHwy: 28,
    mpgCombined: 24,
    fuelType: "Gasoline",
    horsepower: 300,
    torque: 310,
    engine: "2.3L EcoBoost I4",
    transmission: "10-Speed Auto",
    drivetrain: "4WD",
    seatingCapacity: 7,
    cargoFt3: 18.2,
    towingLbs: 5300,
    zeroToSixty: 7.0,
    topSpeed: 143,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 6,
    resaleScore: 7,
    safetyScore: 4,
    features: [
      "3-Row Seating",
      "13.2-inch Touchscreen",
      "Ford Co-Pilot360",
      "Tri-Zone Climate Control",
      "B&O Premium Audio",
      "Panoramic Vista Roof",
      "Power-Folding Third Row",
      "Hands-Free Liftgate",
    ],
  },

  // ── Chevrolet ─────────────────────────────────────────────────────
  {
    make: "Chevrolet",
    model: "Silverado 1500",
    year: 2024,
    bodyStyle: "Truck",
    msrpStart: 36800,
    msrpEnd: 73095,
    mpgCity: 18,
    mpgHwy: 23,
    mpgCombined: 20,
    fuelType: "Gasoline",
    horsepower: 355,
    torque: 383,
    engine: "5.3L V8",
    transmission: "10-Speed Auto",
    drivetrain: "4WD",
    seatingCapacity: 6,
    cargoFt3: 0,
    towingLbs: 13300,
    zeroToSixty: 6.8,
    topSpeed: 110,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 7,
    resaleScore: 8,
    safetyScore: 4,
    features: [
      "Super Cruise Hands-Free",
      "13.4-inch Touchscreen",
      "Multi-Flex Tailgate",
      "Trailering Camera System",
      "Bose Premium Audio",
      "Heated & Ventilated Seats",
      "Wireless Phone Charging",
      "Z71 Off-Road Package",
    ],
  },
  {
    make: "Chevrolet",
    model: "Equinox",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 26995,
    msrpEnd: 35295,
    mpgCity: 25,
    mpgHwy: 30,
    mpgCombined: 27,
    fuelType: "Gasoline",
    horsepower: 175,
    torque: 184,
    engine: "1.5L Turbo I4",
    transmission: "6-Speed Auto",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 29.9,
    towingLbs: 1500,
    zeroToSixty: 9.1,
    topSpeed: 122,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 7,
    resaleScore: 6,
    safetyScore: 5,
    features: [
      "Chevy Safety Assist",
      "11.3-inch Touchscreen",
      "Wireless Apple CarPlay",
      "Heated Front Seats",
      "Power Liftgate",
      "Surround Vision Camera",
      "Bose Premium Audio",
      "Adaptive Cruise Control",
    ],
  },
  {
    make: "Chevrolet",
    model: "Tahoe",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 56200,
    msrpEnd: 80600,
    mpgCity: 15,
    mpgHwy: 20,
    mpgCombined: 17,
    fuelType: "Gasoline",
    horsepower: 355,
    torque: 383,
    engine: "5.3L V8",
    transmission: "10-Speed Auto",
    drivetrain: "4WD",
    seatingCapacity: 8,
    cargoFt3: 25.5,
    towingLbs: 8400,
    zeroToSixty: 7.0,
    topSpeed: 120,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 7,
    resaleScore: 8,
    safetyScore: 4,
    features: [
      "Super Cruise Hands-Free",
      "Magnetic Ride Control",
      "17.7-inch Touchscreen",
      "3-Row Seating",
      "Power Sliding Center Console",
      "Bose Premium Audio",
      "Rear-Seat Entertainment",
      "Adaptive Air Suspension",
    ],
  },
  {
    make: "Chevrolet",
    model: "Camaro",
    year: 2024,
    bodyStyle: "Coupe",
    msrpStart: 27495,
    msrpEnd: 78395,
    mpgCity: 19,
    mpgHwy: 29,
    mpgCombined: 22,
    fuelType: "Gasoline",
    horsepower: 335,
    torque: 284,
    engine: "3.6L V6",
    transmission: "10-Speed Auto",
    drivetrain: "RWD",
    seatingCapacity: 4,
    cargoFt3: 9.1,
    towingLbs: 0,
    zeroToSixty: 5.1,
    topSpeed: 165,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 7,
    resaleScore: 7,
    safetyScore: 4,
    features: [
      "Performance Data Recorder",
      "Magnetic Ride Control",
      "Brembo Performance Brakes",
      "Drive Mode Selector",
      "Launch Control",
      "Apple CarPlay & Android Auto",
      "Bose Premium Audio",
      "RECARO Performance Seats",
    ],
  },
  {
    make: "Chevrolet",
    model: "Corvette",
    year: 2024,
    bodyStyle: "Coupe",
    msrpStart: 68300,
    msrpEnd: 114795,
    mpgCity: 16,
    mpgHwy: 24,
    mpgCombined: 19,
    fuelType: "Gasoline",
    horsepower: 495,
    torque: 470,
    engine: "6.2L V8 (mid-engine)",
    transmission: "8-Speed Dual-Clutch",
    drivetrain: "RWD",
    seatingCapacity: 2,
    cargoFt3: 12.6,
    towingLbs: 0,
    zeroToSixty: 2.9,
    topSpeed: 194,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 7,
    resaleScore: 9,
    safetyScore: 4,
    features: [
      "Mid-Engine Layout",
      "Magnetic Ride Control 4.0",
      "Performance Traction Management",
      "Z51 Performance Package",
      "Front Lift System",
      "Bose Premium Audio",
      "Launch Control",
      "Removable Roof Panel",
    ],
  },

  // ── Tesla ─────────────────────────────────────────────────────────
  {
    make: "Tesla",
    model: "Model 3",
    year: 2024,
    bodyStyle: "Sedan",
    msrpStart: 38990,
    msrpEnd: 53990,
    mpgCity: 138,
    mpgHwy: 126,
    mpgCombined: 132,
    fuelType: "Electric",
    rangeMiles: 341,
    horsepower: 286,
    torque: 317,
    engine: "Single Electric Motor",
    transmission: "Single-Speed",
    drivetrain: "RWD",
    seatingCapacity: 5,
    cargoFt3: 21.0,
    towingLbs: 0,
    zeroToSixty: 5.8,
    topSpeed: 140,
    warranty: { basic: "4 yr / 50,000 mi", powertrain: "8 yr / 120,000 mi" },
    reliabilityScore: 8,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "Autopilot Standard",
      "15-inch Center Touchscreen",
      "Glass Roof",
      "Premium Audio (17 speakers)",
      "Heated Front & Rear Seats",
      "Over-the-Air Updates",
      "Supercharger Network Access",
      "Sentry Mode Surveillance",
    ],
  },
  {
    make: "Tesla",
    model: "Model Y",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 44990,
    msrpEnd: 53490,
    mpgCity: 127,
    mpgHwy: 117,
    mpgCombined: 122,
    fuelType: "Electric",
    rangeMiles: 320,
    horsepower: 384,
    torque: 376,
    engine: "Dual Electric Motors",
    transmission: "Single-Speed",
    drivetrain: "AWD",
    seatingCapacity: 7,
    cargoFt3: 76.2,
    towingLbs: 3500,
    zeroToSixty: 4.8,
    topSpeed: 135,
    warranty: { basic: "4 yr / 50,000 mi", powertrain: "8 yr / 120,000 mi" },
    reliabilityScore: 8,
    resaleScore: 8,
    safetyScore: 5,
    features: [
      "Optional 7-Seat Configuration",
      "Autopilot Standard",
      "15-inch Center Touchscreen",
      "Panoramic Glass Roof",
      "Power Liftgate",
      "Heated & Ventilated Seats",
      "Over-the-Air Updates",
      "Supercharger Network Access",
    ],
  },
  {
    make: "Tesla",
    model: "Model S",
    year: 2024,
    bodyStyle: "Sedan",
    msrpStart: 74990,
    msrpEnd: 94990,
    mpgCity: 124,
    mpgHwy: 115,
    mpgCombined: 120,
    fuelType: "Electric",
    rangeMiles: 405,
    horsepower: 670,
    torque: 723,
    engine: "Tri Electric Motors",
    transmission: "Single-Speed",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 28.0,
    towingLbs: 0,
    zeroToSixty: 3.1,
    topSpeed: 155,
    warranty: { basic: "4 yr / 50,000 mi", powertrain: "8 yr / 150,000 mi" },
    reliabilityScore: 7,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "Yoke or Round Steering Wheel",
      "17-inch Cinematic Display",
      "Rear Touchscreen",
      "Tri-Zone Climate Control",
      "22-Speaker Premium Audio",
      "Autopilot Standard",
      "HEPA Air Filtration",
      "Supercharger Network Access",
    ],
  },
  {
    make: "Tesla",
    model: "Cybertruck",
    year: 2024,
    bodyStyle: "Truck",
    msrpStart: 79990,
    msrpEnd: 99990,
    mpgCity: 70,
    mpgHwy: 67,
    mpgCombined: 68,
    fuelType: "Electric",
    rangeMiles: 340,
    horsepower: 600,
    torque: 7435,
    engine: "Dual Electric Motors",
    transmission: "Single-Speed",
    drivetrain: "AWD",
    seatingCapacity: 6,
    cargoFt3: 0,
    towingLbs: 11000,
    zeroToSixty: 4.1,
    topSpeed: 112,
    warranty: { basic: "4 yr / 50,000 mi", powertrain: "8 yr / 150,000 mi" },
    reliabilityScore: 6,
    resaleScore: 7,
    safetyScore: 4,
    features: [
      "Stainless Steel Exoskeleton",
      "Adaptive Air Suspension",
      "Steer-by-Wire System",
      "Rear-Wheel Steering",
      "18.5-inch Touchscreen",
      "Bulletproof Glass",
      "Powershare Bidirectional Charging",
      "Locking Tonneau Cover",
    ],
  },

  // ── BMW ───────────────────────────────────────────────────────────
  {
    make: "BMW",
    model: "3 Series",
    year: 2024,
    bodyStyle: "Sedan",
    msrpStart: 44500,
    msrpEnd: 60900,
    mpgCity: 26,
    mpgHwy: 36,
    mpgCombined: 30,
    fuelType: "Gasoline",
    horsepower: 255,
    torque: 295,
    engine: "2.0L Turbo I4",
    transmission: "8-Speed Auto",
    drivetrain: "RWD",
    seatingCapacity: 5,
    cargoFt3: 17.0,
    towingLbs: 0,
    zeroToSixty: 5.6,
    topSpeed: 155,
    warranty: { basic: "4 yr / 50,000 mi", powertrain: "4 yr / 50,000 mi" },
    reliabilityScore: 7,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "BMW iDrive 8.5",
      "14.9-inch Curved Display",
      "BMW Live Cockpit Pro",
      "Driving Assistant Plus",
      "Harman Kardon Audio",
      "Wireless Apple CarPlay",
      "Sport Seats",
      "Adaptive M Suspension",
    ],
  },
  {
    make: "BMW",
    model: "X5",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 65200,
    msrpEnd: 109300,
    mpgCity: 21,
    mpgHwy: 26,
    mpgCombined: 23,
    fuelType: "Gasoline",
    horsepower: 375,
    torque: 398,
    engine: "3.0L Turbo I6",
    transmission: "8-Speed Auto",
    drivetrain: "AWD",
    seatingCapacity: 7,
    cargoFt3: 33.9,
    towingLbs: 7200,
    zeroToSixty: 5.3,
    topSpeed: 130,
    warranty: { basic: "4 yr / 50,000 mi", powertrain: "4 yr / 50,000 mi" },
    reliabilityScore: 7,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "BMW iDrive 8.5",
      "Curved Display Cockpit",
      "Adaptive 2-Axle Air Suspension",
      "Panoramic Sky Lounge Roof",
      "Harman Kardon Audio",
      "Heated & Ventilated Seats",
      "Driving Assistant Professional",
      "Optional 3rd Row",
    ],
  },

  // ── Mercedes-Benz ─────────────────────────────────────────────────
  {
    "make": "Mercedes-Benz",
    "model": "C-Class",
    year: 2024,
    bodyStyle: "Sedan",
    msrpStart: 47100,
    msrpEnd: 56550,
    mpgCity: 25,
    mpgHwy: 35,
    mpgCombined: 29,
    fuelType: "Gasoline",
    horsepower: 255,
    torque: 295,
    engine: "2.0L Turbo I4",
    transmission: "9-Speed Auto",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 12.6,
    towingLbs: 0,
    zeroToSixty: 5.9,
    topSpeed: 130,
    warranty: { basic: "4 yr / 50,000 mi", powertrain: "4 yr / 50,000 mi" },
    reliabilityScore: 7,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "MBUX Infotainment",
      "11.9-inch Portrait Touchscreen",
      "12.3-inch Digital Cluster",
      "Burmester Premium Audio",
      "Heated Front Seats",
      "Active Brake Assist",
      "Wireless Apple CarPlay",
      "64-Color Ambient Lighting",
    ],
  },
  {
    "make": "Mercedes-Benz",
    "model": "GLE",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 60500,
    msrpEnd: 88500,
    mpgCity: 19,
    mpgHwy: 26,
    mpgCombined: 22,
    fuelType: "Gasoline",
    horsepower: 375,
    torque: 369,
    engine: "3.0L Turbo I6",
    transmission: "9-Speed Auto",
    drivetrain: "AWD",
    seatingCapacity: 7,
    cargoFt3: 33.3,
    towingLbs: 7700,
    zeroToSixty: 5.5,
    topSpeed: 130,
    warranty: { basic: "4 yr / 50,000 mi", powertrain: "4 yr / 50,000 mi" },
    reliabilityScore: 7,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "MBUX Hyperscreen Available",
      "Air Body Control Suspension",
      "Burmester 3D Surround Audio",
      "Active Distance Assist",
      "Panoramic Sunroof",
      "Heated & Ventilated Seats",
      "Optional 3rd Row",
      "Energizing Comfort Package",
    ],
  },

  // ── Audi ──────────────────────────────────────────────────────────
  {
    make: "Audi",
    model: "A4",
    year: 2024,
    bodyStyle: "Sedan",
    msrpStart: 42100,
    msrpEnd: 53800,
    mpgCity: 24,
    mpgHwy: 31,
    mpgCombined: 27,
    fuelType: "Gasoline",
    horsepower: 261,
    torque: 273,
    engine: "2.0L Turbo I4",
    transmission: "7-Speed Dual-Clutch",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 12.0,
    towingLbs: 0,
    zeroToSixty: 5.6,
    topSpeed: 130,
    warranty: { basic: "4 yr / 50,000 mi", powertrain: "4 yr / 50,000 mi" },
    reliabilityScore: 7,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "Quattro AWD Standard",
      "Virtual Cockpit Plus",
      "MMI Touch Display",
      "Bang & Olufsen Audio",
      "Audi Pre Sense Front",
      "Heated Front Seats",
      "Apple CarPlay & Android Auto",
      "S Line Trim Available",
    ],
  },
  {
    make: "Audi",
    model: "Q5",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 45400,
    msrpEnd: 58400,
    mpgCity: 23,
    mpgHwy: 28,
    mpgCombined: 25,
    fuelType: "Gasoline",
    horsepower: 261,
    torque: 273,
    engine: "2.0L Turbo I4",
    transmission: "7-Speed Dual-Clutch",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 25.8,
    towingLbs: 4400,
    zeroToSixty: 5.7,
    topSpeed: 130,
    warranty: { basic: "4 yr / 50,000 mi", powertrain: "4 yr / 50,000 mi" },
    reliabilityScore: 7,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "Quattro AWD Standard",
      "Virtual Cockpit Plus",
      "10.1-inch MMI Display",
      "Bang & Olufsen Audio",
      "Panoramic Sunroof",
      "Audi Pre Sense Front",
      "Power Liftgate",
      "Heated Front Seats",
    ],
  },

  // ── Lexus ─────────────────────────────────────────────────────────
  {
    make: "Lexus",
    model: "RX",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 49950,
    msrpEnd: 67500,
    mpgCity: 21,
    mpgHwy: 28,
    mpgCombined: 24,
    fuelType: "Gasoline",
    horsepower: 275,
    torque: 317,
    engine: "2.4L Turbo I4",
    transmission: "8-Speed Auto",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 29.6,
    towingLbs: 3500,
    zeroToSixty: 7.2,
    topSpeed: 124,
    warranty: { basic: "4 yr / 50,000 mi", powertrain: "6 yr / 70,000 mi" },
    reliabilityScore: 9,
    resaleScore: 9,
    safetyScore: 5,
    features: [
      "Lexus Safety System+ 3.0",
      "14-inch Touchscreen",
      "Mark Levinson Audio",
      "Panoramic Moonroof",
      "Heated & Ventilated Seats",
      "Wireless Apple CarPlay",
      "Hands-Free Liftgate",
      "Head-Up Display",
    ],
  },
  {
    make: "Lexus",
    model: "ES",
    year: 2024,
    bodyStyle: "Sedan",
    msrpStart: 42990,
    msrpEnd: 53800,
    mpgCity: 22,
    mpgHwy: 32,
    mpgCombined: 26,
    fuelType: "Gasoline",
    horsepower: 302,
    torque: 267,
    engine: "3.5L V6",
    transmission: "8-Speed Auto",
    drivetrain: "FWD",
    seatingCapacity: 5,
    cargoFt3: 16.7,
    towingLbs: 0,
    zeroToSixty: 6.6,
    topSpeed: 130,
    warranty: { basic: "4 yr / 50,000 mi", powertrain: "6 yr / 70,000 mi" },
    reliabilityScore: 9,
    resaleScore: 8,
    safetyScore: 5,
    features: [
      "Lexus Safety System+ 2.5",
      "12.3-inch Touchscreen",
      "Mark Levinson 17-Speaker Audio",
      "NuLuxe Trimmed Seats",
      "Heated & Ventilated Seats",
      "Wireless Apple CarPlay",
      "Bird's Eye View Camera",
      "Adaptive Variable Suspension",
    ],
  },

  // ── Mazda ─────────────────────────────────────────────────────────
  {
    make: "Mazda",
    model: "CX-5",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 28770,
    msrpEnd: 41100,
    mpgCity: 26,
    mpgHwy: 31,
    mpgCombined: 28,
    fuelType: "Gasoline",
    horsepower: 187,
    torque: 186,
    engine: "2.5L I4",
    transmission: "6-Speed Auto",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 30.8,
    towingLbs: 2000,
    zeroToSixty: 8.0,
    topSpeed: 125,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 8,
    resaleScore: 8,
    safetyScore: 5,
    features: [
      "i-Activsense Safety Suite",
      "i-Activ AWD",
      "10.25-inch Center Display",
      "Bose 10-Speaker Audio",
      "Power Liftgate",
      "Heated Front Seats",
      "Apple CarPlay & Android Auto",
      "Head-Up Display",
    ],
  },
  {
    make: "Mazda",
    model: "Mazda 3",
    year: 2024,
    bodyStyle: "Sedan",
    msrpStart: 24170,
    msrpEnd: 36750,
    mpgCity: 28,
    mpgHwy: 36,
    mpgCombined: 31,
    fuelType: "Gasoline",
    horsepower: 191,
    torque: 186,
    engine: "2.5L I4",
    transmission: "6-Speed Auto",
    drivetrain: "FWD",
    seatingCapacity: 5,
    cargoFt3: 13.2,
    towingLbs: 0,
    zeroToSixty: 7.5,
    topSpeed: 130,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 8,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "i-Activsense Safety Suite",
      "8.8-inch Center Display",
      "Bose 12-Speaker Audio",
      "Heated Leather Seats",
      "Apple CarPlay & Android Auto",
      "Active Driving Display",
      "Power Moonroof",
      "Adaptive Front Lighting",
    ],
  },

  // ── Subaru ────────────────────────────────────────────────────────
  {
    make: "Subaru",
    model: "Outback",
    year: 2024,
    bodyStyle: "Wagon",
    msrpStart: 28895,
    msrpEnd: 43295,
    mpgCity: 26,
    mpgHwy: 32,
    mpgCombined: 29,
    fuelType: "Gasoline",
    horsepower: 182,
    torque: 176,
    engine: "2.5L Boxer-4",
    transmission: "CVT",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 32.5,
    towingLbs: 2700,
    zeroToSixty: 8.7,
    topSpeed: 130,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 8,
    resaleScore: 9,
    safetyScore: 5,
    features: [
      "EyeSight Driver Assist",
      "Symmetrical AWD Standard",
      "X-Mode Off-Road",
      "11.6-inch Touchscreen",
      "Harman Kardon Audio",
      "Heated Front & Rear Seats",
      "Roof Rails with Tie-Downs",
      "Power Liftgate",
    ],
  },
  {
    make: "Subaru",
    model: "Forester",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 27095,
    msrpEnd: 37670,
    mpgCity: 26,
    mpgHwy: 33,
    mpgCombined: 29,
    fuelType: "Gasoline",
    horsepower: 182,
    torque: 176,
    engine: "2.5L Boxer-4",
    transmission: "CVT",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 26.9,
    towingLbs: 1500,
    zeroToSixty: 8.5,
    topSpeed: 125,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 8,
    resaleScore: 9,
    safetyScore: 5,
    features: [
      "EyeSight Driver Assist",
      "Symmetrical AWD Standard",
      "X-Mode Off-Road",
      "Panoramic Moonroof",
      "Heated Front Seats",
      "Apple CarPlay & Android Auto",
      "Reverse Automatic Braking",
      "DriverFocus Distraction Mitigation",
    ],
  },

  // ── Hyundai ───────────────────────────────────────────────────────
  {
    make: "Hyundai",
    model: "Elantra",
    year: 2024,
    bodyStyle: "Sedan",
    msrpStart: 21625,
    msrpEnd: 28500,
    mpgCity: 33,
    mpgHwy: 42,
    mpgCombined: 36,
    fuelType: "Gasoline",
    horsepower: 147,
    torque: 132,
    engine: "2.0L I4",
    transmission: "CVT",
    drivetrain: "FWD",
    seatingCapacity: 5,
    cargoFt3: 14.2,
    towingLbs: 0,
    zeroToSixty: 8.3,
    topSpeed: 125,
    warranty: { basic: "5 yr / 60,000 mi", powertrain: "10 yr / 100,000 mi" },
    reliabilityScore: 8,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "SmartSense Safety Suite",
      "Forward Collision-Avoidance",
      "10.25-inch Touchscreen",
      "Bose Premium Audio",
      "Wireless Apple CarPlay",
      "Heated Front Seats",
      "Adaptive Cruise Control",
      "Highway Driving Assist",
    ],
  },
  {
    make: "Hyundai",
    model: "Tucson",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 27250,
    msrpEnd: 38780,
    mpgCity: 25,
    mpgHwy: 32,
    mpgCombined: 28,
    fuelType: "Gasoline",
    horsepower: 187,
    torque: 178,
    engine: "2.5L I4",
    transmission: "8-Speed Auto",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 38.7,
    towingLbs: 2000,
    zeroToSixty: 8.8,
    topSpeed: 125,
    warranty: { basic: "5 yr / 60,000 mi", powertrain: "10 yr / 100,000 mi" },
    reliabilityScore: 8,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "SmartSense Safety Suite",
      "HTRAC AWD",
      "10.25-inch Dual Displays",
      "Bose Premium Audio",
      "Heated & Ventilated Seats",
      "Power Liftgate",
      "Highway Driving Assist 2",
      "Surround View Monitor",
    ],
  },

  // ── Kia ───────────────────────────────────────────────────────────
  {
    make: "Kia",
    model: "Sorento",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 31990,
    msrpEnd: 47090,
    mpgCity: 22,
    mpgHwy: 29,
    mpgCombined: 25,
    fuelType: "Gasoline",
    horsepower: 281,
    torque: 311,
    engine: "2.5L Turbo I4",
    transmission: "8-Speed Dual-Clutch",
    drivetrain: "AWD",
    seatingCapacity: 7,
    cargoFt3: 12.6,
    towingLbs: 3500,
    zeroToSixty: 6.2,
    topSpeed: 130,
    warranty: { basic: "5 yr / 60,000 mi", powertrain: "10 yr / 100,000 mi" },
    reliabilityScore: 8,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "3-Row Seating",
      "Kia Drive Wise Suite",
      "12.3-inch Touchscreen",
      "Bose 12-Speaker Audio",
      "Highway Driving Assist 2",
      "Heated & Ventilated Seats",
      "Wireless Apple CarPlay",
      "Around-View Monitor",
    ],
  },

  // ── Nissan ────────────────────────────────────────────────────────
  {
    make: "Nissan",
    model: "Altima",
    year: 2024,
    bodyStyle: "Sedan",
    msrpStart: 26370,
    msrpEnd: 35190,
    mpgCity: 27,
    mpgHwy: 39,
    mpgCombined: 32,
    fuelType: "Gasoline",
    horsepower: 188,
    torque: 180,
    engine: "2.5L I4",
    transmission: "CVT",
    drivetrain: "FWD",
    seatingCapacity: 5,
    cargoFt3: 15.4,
    towingLbs: 0,
    zeroToSixty: 7.6,
    topSpeed: 130,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 7,
    resaleScore: 6,
    safetyScore: 5,
    features: [
      "Nissan Safety Shield 360",
      "ProPILOT Assist",
      "12.3-inch Touchscreen",
      "Bose Premium Audio",
      "Wireless Apple CarPlay",
      "Heated Front Seats",
      "Intelligent Cruise Control",
      "Around View Monitor",
    ],
  },
  {
    make: "Nissan",
    model: "Rogue",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 28850,
    msrpEnd: 39990,
    mpgCity: 30,
    mpgHwy: 37,
    mpgCombined: 33,
    fuelType: "Gasoline",
    horsepower: 201,
    torque: 225,
    engine: "1.5L Turbo I3",
    transmission: "CVT",
    drivetrain: "AWD",
    seatingCapacity: 5,
    cargoFt3: 36.5,
    towingLbs: 1500,
    zeroToSixty: 8.2,
    topSpeed: 125,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 7,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "Nissan Safety Shield 360",
      "ProPILOT Assist 2.0",
      "Intelligent AWD",
      "12.3-inch Touchscreen",
      "Bose Premium Audio",
      "Heated & Ventilated Seats",
      "Power Panoramic Moonroof",
      "Around View Monitor",
    ],
  },

  // ── Jeep ──────────────────────────────────────────────────────────
  {
    make: "Jeep",
    model: "Wrangler",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 31995,
    msrpEnd: 89990,
    mpgCity: 17,
    mpgHwy: 25,
    mpgCombined: 20,
    fuelType: "Gasoline",
    horsepower: 285,
    torque: 260,
    engine: "3.6L V6",
    transmission: "8-Speed Auto",
    drivetrain: "4WD",
    seatingCapacity: 5,
    cargoFt3: 31.7,
    towingLbs: 3500,
    zeroToSixty: 6.7,
    topSpeed: 112,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 6,
    resaleScore: 9,
    safetyScore: 4,
    features: [
      "Trail-Rated 4x4",
      "Removable Doors & Roof",
      "Electronic Sway Bar Disconnect",
      "Rock-Trac 4WD System",
      "Selec-Trac Full-Time 4WD",
      "12.3-inch Touchscreen",
      "Wireless Apple CarPlay",
      "Tru-Lok Locking Differentials",
    ],
  },
  {
    make: "Jeep",
    model: "Grand Cherokee",
    year: 2024,
    bodyStyle: "SUV",
    msrpStart: 39440,
    msrpEnd: 73190,
    mpgCity: 19,
    mpgHwy: 26,
    mpgCombined: 22,
    fuelType: "Gasoline",
    horsepower: 293,
    torque: 260,
    engine: "3.6L V6",
    transmission: "8-Speed Auto",
    drivetrain: "4WD",
    seatingCapacity: 5,
    cargoFt3: 37.7,
    towingLbs: 6200,
    zeroToSixty: 6.5,
    topSpeed: 130,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 6,
    resaleScore: 7,
    safetyScore: 5,
    features: [
      "Quadra-Lift Air Suspension",
      "Selec-Terrain Traction Mgmt",
      "10.25-inch Touchscreen",
      "Night Vision Camera",
      "McIntosh 19-Speaker Audio",
      "Heated & Ventilated Seats",
      "Hands-Free Power Liftgate",
      "Active Driving Assistance",
    ],
  },

  // ── Ram ───────────────────────────────────────────────────────────
  {
    make: "Ram",
    model: "1500",
    year: 2024,
    bodyStyle: "Truck",
    msrpStart: 41385,
    msrpEnd: 89065,
    mpgCity: 19,
    mpgHwy: 24,
    mpgCombined: 21,
    fuelType: "Gasoline",
    horsepower: 305,
    torque: 269,
    engine: "3.6L V6 eTorque",
    transmission: "8-Speed Auto",
    drivetrain: "4WD",
    seatingCapacity: 6,
    cargoFt3: 0,
    towingLbs: 12750,
    zeroToSixty: 7.0,
    topSpeed: 125,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 7,
    resaleScore: 8,
    safetyScore: 4,
    features: [
      "12-inch Vertical Touchscreen",
      "Active-Level Air Suspension",
      "Multifunction Tailgate",
      "RamBox Cargo Management",
      "Harman Kardon Premium Audio",
      "Heated & Ventilated Seats",
      "Adaptive Cruise w/ Stop & Go",
      "360-Degree Surround View",
    ],
  },

  // ── GMC ───────────────────────────────────────────────────────────
  {
    make: "GMC",
    model: "Sierra 1500",
    year: 2024,
    bodyStyle: "Truck",
    msrpStart: 38000,
    msrpEnd: 89200,
    mpgCity: 18,
    mpgHwy: 23,
    mpgCombined: 20,
    fuelType: "Gasoline",
    horsepower: 355,
    torque: 383,
    engine: "5.3L V8",
    transmission: "10-Speed Auto",
    drivetrain: "4WD",
    seatingCapacity: 6,
    cargoFt3: 0,
    towingLbs: 13200,
    zeroToSixty: 6.8,
    topSpeed: 110,
    warranty: { basic: "3 yr / 36,000 mi", powertrain: "5 yr / 60,000 mi" },
    reliabilityScore: 7,
    resaleScore: 8,
    safetyScore: 4,
    features: [
      "Super Cruise Hands-Free",
      "MultiPro Tailgate",
      "13.4-inch Touchscreen",
      "AT4X Off-Road Package",
      "Bose Premium Audio",
      "Heated & Ventilated Seats",
      "Head-Up Display",
      "ProGrade Trailering",
    ],
  },

  // ── Volkswagen ────────────────────────────────────────────────────
  {
    make: "Volkswagen",
    model: "Jetta",
    year: 2024,
    bodyStyle: "Sedan",
    msrpStart: 21995,
    msrpEnd: 32995,
    mpgCity: 29,
    mpgHwy: 40,
    mpgCombined: 34,
    fuelType: "Gasoline",
    horsepower: 158,
    torque: 184,
    engine: "1.5L Turbo I4",
    transmission: "8-Speed Auto",
    drivetrain: "FWD",
    seatingCapacity: 5,
    cargoFt3: 14.1,
    towingLbs: 0,
    zeroToSixty: 7.6,
    topSpeed: 127,
    warranty: { basic: "4 yr / 50,000 mi", powertrain: "4 yr / 50,000 mi" },
    reliabilityScore: 7,
    resaleScore: 6,
    safetyScore: 5,
    features: [
      "IQ.Drive Assistance Suite",
      "8-inch Digital Cockpit",
      "Beats Premium Audio",
      "Wireless Apple CarPlay",
      "Heated Front Seats",
      "Adaptive Cruise Control",
      "Lane Keeping System",
      "Power Moonroof",
    ],
  },

  // ── Porsche ───────────────────────────────────────────────────────
  {
    make: "Porsche",
    model: "911",
    year: 2024,
    bodyStyle: "Coupe",
    msrpStart: 116050,
    msrpEnd: 251400,
    mpgCity: 18,
    mpgHwy: 24,
    mpgCombined: 20,
    fuelType: "Gasoline",
    horsepower: 379,
    torque: 331,
    engine: "3.0L Twin-Turbo Flat-6",
    transmission: "8-Speed PDK",
    drivetrain: "RWD",
    seatingCapacity: 4,
    cargoFt3: 4.6,
    towingLbs: 0,
    zeroToSixty: 4.0,
    topSpeed: 182,
    warranty: { basic: "4 yr / 50,000 mi", powertrain: "4 yr / 50,000 mi" },
    reliabilityScore: 8,
    resaleScore: 10,
    safetyScore: 4,
    features: [
      "Porsche Active Suspension Mgmt",
      "Sport Chrono Package",
      "Porsche Communication Mgmt",
      "BOSE Surround Sound",
      "Sport Exhaust System",
      "Adaptive Sport Seats",
      "Launch Control",
      "Wet Mode Driving",
    ],
  },
];

/* ── Lookup helpers ─────────────────────────────────────────── */

export function getVehicle(make: string, model: string): VehicleSpec | undefined {
  return vehicleSpecs.find(
    (v) => v.make.toLowerCase() === make.toLowerCase() && v.model.toLowerCase() === model.toLowerCase()
  );
}

export function listMakes(): string[] {
  const set = new Set<string>();
  for (const v of vehicleSpecs) set.add(v.make);
  return Array.from(set).sort();
}

export function listModelsForMake(make: string): string[] {
  return vehicleSpecs
    .filter((v) => v.make.toLowerCase() === make.toLowerCase())
    .map((v) => v.model)
    .sort();
}

/* ── Slug helpers (for ?a=toyota-camry&b=honda-accord URL state) ── */

export function vehicleToSlug(v: VehicleSpec): string {
  return slugify(`${v.make} ${v.model}`);
}

export function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function getVehicleBySlug(slug: string): VehicleSpec | undefined {
  if (!slug) return undefined;
  const target = slug.toLowerCase();
  return vehicleSpecs.find((v) => vehicleToSlug(v) === target);
}
