import { defineField, defineType } from "sanity";

export const post = defineType({
  name: "post",
  title: "Blog Post",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "seo", title: "SEO" },
    { name: "settings", title: "Settings" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "content",
      validation: (r) => r.required().max(120),
    }),
    defineField({
      name: "slug",
      title: "URL Slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "excerpt",
      title: "Excerpt",
      type: "text",
      rows: 3,
      group: "content",
      description: "1–2 sentence teaser shown on the blog index and in social shares.",
      validation: (r) => r.max(220),
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image",
      type: "image",
      group: "content",
      options: { hotspot: true },
      fields: [
        { name: "alt", title: "Alt text", type: "string", validation: (r) => r.required() },
      ],
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "reference",
      group: "content",
      to: [{ type: "category" }],
    }),
    defineField({
      name: "author",
      title: "Author",
      type: "reference",
      group: "content",
      to: [{ type: "author" }],
    }),
    defineField({
      name: "publishedAt",
      title: "Published At",
      type: "datetime",
      group: "content",
      validation: (r) => r.required(),
      initialValue: () => new Date().toISOString(),
    }),
    defineField({
      name: "body",
      title: "Body",
      type: "blockContent",
      group: "content",
    }),
    defineField({
      name: "tags",
      title: "Tags",
      type: "array",
      group: "content",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "relatedPosts",
      title: "Related Posts",
      type: "array",
      group: "content",
      of: [{ type: "reference", to: [{ type: "post" }] }],
      validation: (r) => r.max(3),
    }),

    // SEO group
    defineField({
      name: "seoTitle",
      title: "SEO Title",
      type: "string",
      group: "seo",
      description: "Override the default title in <title>. Aim for 50–60 chars.",
      validation: (r) => r.max(70),
    }),
    defineField({
      name: "seoDescription",
      title: "Meta Description",
      type: "text",
      rows: 3,
      group: "seo",
      description: "Shown in Google results. Aim for 140–160 chars.",
      validation: (r) => r.max(170),
    }),
    defineField({
      name: "focusKeyword",
      title: "Focus Keyword",
      type: "string",
      group: "seo",
      description: "Primary keyword this post targets. Use it in title, intro, headers, and conclusion.",
    }),
    defineField({
      name: "keywords",
      title: "Additional Keywords",
      type: "array",
      group: "seo",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "ogImage",
      title: "Social Share Image (OG)",
      type: "image",
      group: "seo",
      description: "1200×630 image for Twitter/Facebook/LinkedIn shares. Falls back to hero image if empty.",
      options: { hotspot: true },
    }),
    defineField({
      name: "noIndex",
      title: "Hide from search engines",
      type: "boolean",
      group: "seo",
      initialValue: false,
    }),
    defineField({
      name: "canonicalUrl",
      title: "Canonical URL Override",
      type: "url",
      group: "seo",
      description: "Only fill this if this content is republished from another URL.",
    }),

    // Settings
    defineField({
      name: "featured",
      title: "Featured post",
      type: "boolean",
      group: "settings",
      initialValue: false,
    }),

    // ── Auto-publishing bot fields ──
    // Populated by /api/cron/blog-bot when it writes a post. Used by the
    // sister cron /api/cron/blog-bot-unindex to flip the noIndex flag to
    // false once `indexAt` has passed, giving us a 24-hour quality window
    // before Google sees the post.
    defineField({
      name: "botGenerated",
      title: "Generated by blog bot",
      type: "boolean",
      group: "settings",
      initialValue: false,
      description: "Set automatically when the post comes from the auto-publish bot.",
    }),
    defineField({
      name: "indexAt",
      title: "Index from (UTC)",
      type: "datetime",
      group: "settings",
      description:
        "Bot-written posts are noIndex until this timestamp; the unindex cron flips noIndex=false when this passes. Leave blank for manually authored posts.",
    }),
    defineField({
      name: "botRunId",
      title: "Bot run id",
      type: "string",
      group: "settings",
      description: "Internal tracing id from the cron run that created this post.",
      readOnly: true,
    }),
  ],
  preview: {
    select: { title: "title", media: "heroImage", subtitle: "category.title" },
  },
  orderings: [
    { title: "Newest first", name: "publishedDesc", by: [{ field: "publishedAt", direction: "desc" }] },
    { title: "Oldest first", name: "publishedAsc", by: [{ field: "publishedAt", direction: "asc" }] },
  ],
});
