import type { Metadata } from "next";
import Link from "next/link";
import { Check } from "lucide-react";
import Breadcrumbs from "@/components/Breadcrumbs";
import VinSearchForm from "@/components/VinSearchForm";
import RelatedChecks from "@/components/RelatedChecks";

export const metadata: Metadata = {
  title: "Build Sheet by VIN — Original Factory Build Record",
  description:
    "Look up the original factory build sheet for any vehicle by VIN. See every option, package, color code, and factory-installed equipment exactly as ordered.",
  keywords: [
    "build sheet by VIN",
    "factory build sheet",
    "original build record",
    "VIN build data",
    "vehicle factory options",
    "how to get build sheet",
  ],
  alternates: { canonical: "/build-sheet" },
  openGraph: {
    title: "Build Sheet by VIN — Original Factory Build Record",
    description:
      "Look up the original factory build sheet for any vehicle by VIN. See every option, package, color code, and factory-installed equipment.",
    url: "https://www.carcheckervin.com/build-sheet",
    type: "article",
  },
};

const articleSchema = {
  "@context": "https://schema.org",
  "@type": "Article",
  headline: "Build Sheet by VIN",
  description:
    "Learn how to look up the original factory build sheet for any vehicle by VIN, including options, packages, color codes, and equipment.",
  author: {
    "@type": "Organization",
    name: "CarCheckerVIN",
    url: "https://www.carcheckervin.com",
  },
  publisher: {
    "@type": "Organization",
    name: "CarCheckerVIN",
    url: "https://www.carcheckervin.com",
  },
  mainEntityOfPage: {
    "@type": "WebPage",
    "@id": "https://www.carcheckervin.com/build-sheet",
  },
  datePublished: "2026-05-04",
  dateModified: "2026-05-04",
};

export default function BuildSheetPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }}
      />

      <article className="pt-28 pb-16">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <Breadcrumbs
            items={[
              { label: "Home", href: "/" },
              { label: "Build Sheet" },
            ]}
          />

          <h1 className="mt-6 text-4xl sm:text-5xl font-bold text-slate-900 leading-tight">
            Build Sheet by VIN
          </h1>
          <p className="mt-4 text-lg text-slate-700 leading-relaxed">
            A factory build sheet is the internal production document that lists every option, code, and specification for a vehicle as it was assembled at the factory. Unlike the consumer-facing window sticker, the build sheet uses manufacturer option codes that correspond to specific equipment — giving collectors, restorers, and enthusiasts the definitive factory record. Looking up a build sheet by VIN is the most reliable way to verify what a vehicle was originally built with.
          </p>

          <div className="mt-8 p-6 bg-primary-50 rounded-2xl border border-primary-100">
            <h2 className="text-lg font-bold text-slate-900 mb-3">
              Look Up the Factory Build Sheet
            </h2>
            <VinSearchForm size="sm" />
          </div>

          <h2 className="mt-12 text-2xl font-bold text-slate-900">
            What Is a Factory Build Sheet
          </h2>
          <p className="mt-3 text-slate-600 leading-relaxed">
            A factory build sheet — also called a broadcast sheet, build record, or window data sheet — is a production document generated by the manufacturer&rsquo;s assembly plant for each individual vehicle. It travels with the vehicle through the assembly process and serves as the assembly line&rsquo;s instructions: every worker on the line can see exactly what goes on this specific car.
          </p>
          <p className="mt-3 text-slate-600 leading-relaxed">
            The build sheet is distinct from the window sticker. While the window sticker is a consumer document written in plain language with retail pricing, the build sheet uses internal manufacturer option codes (RPO codes at GM, AO codes at Ford, for example). These codes are far more specific and can identify individual components, production sequences, and plant-specific configurations that never appear on the sticker.
          </p>
          <p className="mt-3 text-slate-600 leading-relaxed">
            Physical build sheets were sometimes hidden inside the vehicle during assembly — stuffed behind seat cushions, under carpet, or inside door panels — where they occasionally survive decades later. Digital build data, however, is preserved in manufacturer databases and can be retrieved electronically through a VIN lookup for most vehicles produced after the 1980s.
          </p>

          <h2 className="mt-12 text-2xl font-bold text-slate-900">
            What the Build Sheet Contains
          </h2>
          <p className="mt-3 text-slate-600 leading-relaxed">
            A factory build sheet contains the complete specification of a vehicle at the component level. The depth of information varies by manufacturer and model year, but typically includes far more granular data than the consumer window sticker.
          </p>
          <ul className="mt-4 space-y-2 text-slate-600">
            <li className="flex gap-2 items-start">
              <Check className="w-5 h-5 text-emerald-500 flex-shrink-0 mt-0.5" />
              <span><strong>Engine and transmission codes</strong> &mdash; specific engine variant, displacement, horsepower rating, and transmission type.</span>
            </li>
            <li className="flex gap-2 items-start">
              <Check className="w-5 h-5 text-emerald-500 flex-shrink-0 mt-0.5" />
              <span><strong>Exterior and interior color codes</strong> &mdash; manufacturer paint codes and interior trim codes for exact color matching.</span>
            </li>
            <li className="flex gap-2 items-start">
              <Check className="w-5 h-5 text-emerald-500 flex-shrink-0 mt-0.5" />
              <span><strong>Option and package codes</strong> &mdash; every factory option installed, from axle ratios to audio systems to appearance packages.</span>
            </li>
            <li className="flex gap-2 items-start">
              <Check className="w-5 h-5 text-emerald-500 flex-shrink-0 mt-0.5" />
              <span><strong>Production plant and date</strong> &mdash; the assembly facility and build date sequence.</span>
            </li>
            <li className="flex gap-2 items-start">
              <Check className="w-5 h-5 text-emerald-500 flex-shrink-0 mt-0.5" />
              <span><strong>Destination and dealer codes</strong> &mdash; the ordering dealer and geographic destination for the vehicle.</span>
            </li>
          </ul>

          <h2 className="mt-12 text-2xl font-bold text-slate-900">
            Build Sheet vs. Window Sticker
          </h2>
          <p className="mt-3 text-slate-600 leading-relaxed">
            The build sheet and window sticker represent two different views of the same underlying factory data. The window sticker is the marketing document — it presents factory options in consumer language with retail pricing and fuel economy ratings. The build sheet is the production document — it presents the same options in manufacturer codes used on the assembly line.
          </p>
          <p className="mt-3 text-slate-600 leading-relaxed">
            For everyday used car buyers, the window sticker lookup provides all the information needed to verify factory equipment and original MSRP. The build sheet becomes essential for enthusiasts, collectors, and restorers who need to verify matching-numbers configurations or source correct original-spec replacement parts.
          </p>
          <p className="mt-3 text-slate-600 leading-relaxed">
            Combine a build sheet lookup with a full{" "}
            <Link href="/vin-check" className="text-primary-600 hover:underline font-medium">
              VIN history report
            </Link>{" "}
            and an{" "}
            <Link href="/accident-history-check" className="text-primary-600 hover:underline font-medium">
              accident history check
            </Link>{" "}
            to get both the factory origin and the subsequent history of any vehicle.
          </p>

          <h2 className="mt-12 text-2xl font-bold text-slate-900">
            How Build Sheets Help Collectors &amp; Restorers
          </h2>
          <p className="mt-3 text-slate-600 leading-relaxed">
            For classic car collectors, build sheet verification can mean the difference between a correct, documented car and an undocumented clone. High-value muscle cars, limited editions, and special-order vehicles often command premiums of tens of thousands of dollars over otherwise identical unverified examples. The build sheet provides the factory documentation that supports authenticity claims.
          </p>
          <p className="mt-3 text-slate-600 leading-relaxed">
            Restorers use build data to source correct original-specification parts. A 1969 Camaro Z/28 with specific factory options requires different components than a base model — the build sheet identifies the correct part numbers, colors, and assembly specifications. This level of detail ensures a show-quality restoration that can withstand judging scrutiny.
          </p>
          <p className="mt-3 text-slate-600 leading-relaxed">
            Pair the build sheet data with a{" "}
            <Link href="/salvage-title-check" className="text-primary-600 hover:underline font-medium">
              salvage title check
            </Link>{" "}
            and an{" "}
            <Link href="/odometer-check" className="text-primary-600 hover:underline font-medium">
              odometer check
            </Link>{" "}
            to verify both the factory configuration and the full ownership and damage history of a collectible vehicle.
          </p>

          <h2 className="mt-12 text-2xl font-bold text-slate-900">
            Decoding Your VIN Build Data
          </h2>
          <p className="mt-3 text-slate-600 leading-relaxed">
            The 17-character VIN itself encodes a subset of the build data: the World Manufacturer Identifier (positions 1–3), vehicle descriptor section (positions 4–8), check digit (position 9), model year (position 10), plant (position 11), and sequential production number (positions 12–17). This embedded data confirms the vehicle&rsquo;s origin and production sequence.
          </p>
          <p className="mt-3 text-slate-600 leading-relaxed">
            However, the VIN alone does not contain option and equipment data — that resides in the manufacturer&rsquo;s build database, linked to the VIN. A build sheet lookup queries that database and returns the complete option list, which is far richer than what can be decoded from the VIN characters alone.
          </p>
          <p className="mt-3 text-slate-600 leading-relaxed">
            For complete pre-purchase protection, always run a build sheet or window sticker lookup alongside a{" "}
            <Link href="/lemon-check" className="text-primary-600 hover:underline font-medium">
              lemon check
            </Link>{" "}
            and a{" "}
            <Link href="/stolen-vehicle-check" className="text-primary-600 hover:underline font-medium">
              stolen vehicle check
            </Link>
            .
          </p>
        </div>
      </article>

      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 mt-12 mb-4">
        <RelatedChecks exclude="/build-sheet" />
      </div>

      <section className="py-14 bg-slate-50">
        <div className="max-w-2xl mx-auto px-4 text-center">
          <h2 className="text-2xl font-bold text-slate-900 mb-2">
            Look Up the Factory Build Sheet
          </h2>
          <p className="text-slate-700 mb-6">
            Enter a 17-character VIN to retrieve the original factory build data, option codes, and equipment list.
          </p>
          <VinSearchForm size="sm" />
        </div>
      </section>
    </>
  );
}
